<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Create an Account_cart_ctBtn</name>
   <tag></tag>
   <elementGuidId>0794e4f3-abd3-4b4d-af59-c8bdafc245e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='idBody']/app-root/app-pack-back-main/app-pack-back-header/header/div/div/div/div[2]/ul[2]/li[9]/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.cart_ctBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>004f8e09-98ef-4c06-96f7-cc5e57a9a12a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./assets/images/pack-back/white/cart_image.svg</value>
      <webElementGuid>66955e1b-9c8c-48f4-be2d-6b25de6aee4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart_ctBtn</value>
      <webElementGuid>85a8d4fa-607b-4254-9ceb-f622a8ddd221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idBody&quot;)/app-root[1]/app-pack-back-main[@class=&quot;ng-star-inserted&quot;]/app-pack-back-header[1]/header[1]/div[@class=&quot;web-hd&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;pd-l-00 header-right&quot;]/div[@class=&quot;logpart pl270&quot;]/ul[@class=&quot;header-logpart&quot;]/li[@class=&quot;circle-icon&quot;]/div[@class=&quot;roundBtn roundBtnwhite bluue-btn c-pointer&quot;]/span[1]/img[@class=&quot;cart_ctBtn&quot;]</value>
      <webElementGuid>ce5b6810-8a5e-4478-8e86-282fa6df3db7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='idBody']/app-root/app-pack-back-main/app-pack-back-header/header/div/div/div/div[2]/ul[2]/li[9]/div/span/img</value>
      <webElementGuid>5bfd3ce5-cff3-4fef-961b-74dda994f41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>41d2ceb8-dd91-48ae-9955-ce56cce28c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './assets/images/pack-back/white/cart_image.svg']</value>
      <webElementGuid>1f89a5a0-79d0-4821-bd74-9b487f8acb61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
