<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invoice Address_address1</name>
   <tag></tag>
   <elementGuidId>e32f36fe-6a58-4640-9c73-997abc469245</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b46c150-b09c-4f64-b9a3-6978883de776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ec89094-c28c-40c1-96a8-63e422ca356f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>b6a981bf-58c0-4fa7-96a9-f0d1fb244c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>bill_addr1</value>
      <webElementGuid>e81abc89-193c-4b62-894c-05dbc215e61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address1</value>
      <webElementGuid>f37786d9-2d15-4bfd-afd1-d2b7c2551880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address1</value>
      <webElementGuid>6d717b4a-0c67-4142-b5be-33d6da769357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>8335d51d-2d74-46fc-acde-c295bab4d43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address1&quot;)</value>
      <webElementGuid>86efda93-a9cf-4ada-8800-dbaa448c094e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address1']</value>
      <webElementGuid>8efe819c-0c38-44b0-8de1-642d3290d4d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-checkout/div/div/div/div/div/div/div/div/div[2]/div[3]/div/form/div[3]/div[2]/input</value>
      <webElementGuid>f25cc947-b343-400f-8e1f-3c3e96a2a79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/form/div[3]/div[2]/input</value>
      <webElementGuid>2eb2986b-c482-476a-bea4-48a5bb6c96d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address1' and @name = 'address1']</value>
      <webElementGuid>72a1e7c7-571d-4d1b-ab18-b3ade294d659</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
