<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_180.00_col-sm-1 col-md-1 text-center</name>
   <tag></tag>
   <elementGuidId>d3a67ebf-ce1d-459f-a1c0-38effec3e52c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='rightcontent']/app-cart/div/div/div/div/div/div/table/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2181e539-042f-4ff9-8604-54a3d7b660c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-sm-1 col-md-1 text-center</value>
      <webElementGuid>8937c78c-ceee-438a-a43f-e9dacbcd6ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightcontent&quot;)/app-cart[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;ptt00 mh900 pickup-part pack-back-part row m0&quot;]/div[@class=&quot;row mg_tr&quot;]/div[@class=&quot;col-12 col-md-12 col-lg-8 col-xl-8 mb-3&quot;]/div[@class=&quot;card table_card ml10&quot;]/table[@class=&quot;table productTable d-none d-sm-none d-xs-none d-lg-block d-md-block d-xl-block d-xxl-block&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;col-sm-1 col-md-1 text-center&quot;]</value>
      <webElementGuid>db4f7d04-c604-4178-81b9-1ef640ed24c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-cart/div/div/div/div/div/div/table/tbody/tr/td[3]</value>
      <webElementGuid>b0985396-13cf-4168-a626-700264e2cf08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$180.00'])[3]/following::td[1]</value>
      <webElementGuid>5b03dd6e-e9a3-465a-8b98-0d43da164ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Would you like us to ship you a replacement for this item when you return it for recycling?'])[2]/following::td[2]</value>
      <webElementGuid>b6fd8079-efa8-4d4f-ae4a-5a12da8dd197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$180.00'])[4]/preceding::td[1]</value>
      <webElementGuid>908af9cc-4ef0-43e5-b98d-533632bb784a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Summary'])[1]/preceding::td[3]</value>
      <webElementGuid>f1bfb3d2-4943-42c2-9c94-572dea474f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>9f135a38-230c-4a22-a45d-e64a75a7b40b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
