<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Pack Back CFLLED Recycling Box - LargeAu_b7ce78</name>
   <tag></tag>
   <elementGuidId>04d81549-b0d7-4187-9a75-b68e45b03f4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='rightcontent']/app-cart/div/div/div/div/div/div/table/tbody/tr[2]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0fa173dd-2ec7-4897-b440-15b6730d9d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-sm-8 col-md-6</value>
      <webElementGuid>9666eca9-5186-404d-bd9e-82868ecb814c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pack Back CFL/LED Recycling Box - LargeAutomatic Replenishment: Would you like us to ship you a replacement for this item when you return it for recycling?</value>
      <webElementGuid>5f698719-19c2-4aa3-a4a1-ff23c48a6949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightcontent&quot;)/app-cart[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;ptt00 mh900 pickup-part pack-back-part row m0&quot;]/div[@class=&quot;row mg_tr&quot;]/div[@class=&quot;col-12 col-md-12 col-lg-8 col-xl-8 mb-3&quot;]/div[@class=&quot;card table_card ml10&quot;]/table[@class=&quot;table productTable d-none d-sm-none d-xs-none d-lg-block d-md-block d-xl-block d-xxl-block&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;col-sm-8 col-md-6&quot;]</value>
      <webElementGuid>e3095d43-7b31-4eca-b4d7-bbb63eac45ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-cart/div/div/div/div/div/div/table/tbody/tr[2]/td</value>
      <webElementGuid>43d600b2-e9a9-4a8c-95ed-27c6c923d1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$180.00'])[4]/following::td[2]</value>
      <webElementGuid>42a10eae-0b15-45e8-8b08-7f2ae69fce0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$180.00'])[3]/following::td[4]</value>
      <webElementGuid>742c0d7b-f6e7-4e73-a1ce-11e8c276cebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>4729d311-bc03-463b-88ad-947971171769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Pack Back CFL/LED Recycling Box - LargeAutomatic Replenishment: Would you like us to ship you a replacement for this item when you return it for recycling?' or . = 'Pack Back CFL/LED Recycling Box - LargeAutomatic Replenishment: Would you like us to ship you a replacement for this item when you return it for recycling?')]</value>
      <webElementGuid>560a81b7-9ef6-40ae-9783-a16b09d7e3a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
