<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Pack Back How It Works</name>
   <tag></tag>
   <elementGuidId>6b8b1361-50a7-460b-93c4-5f9f7de834be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='component-heading-2263']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#component-heading-2263</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>7e6976a6-fee8-4bb9-bc26-80b721c183a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>eck-entity entity-type-component entity-bundle-heading entity--component-heading view-mode--default entity--component-heading-default entity-heading-2263 from-parent--field-components background--component-heading-2263 text-transform--uppercase</value>
      <webElementGuid>75be1b0e-f811-4c4a-8286-d3e7e2c226dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>component-heading-2263</value>
      <webElementGuid>3a3f1f54-3168-4ebe-ab8c-08a4a61496ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pack Back: How It Works</value>
      <webElementGuid>2831de1c-75d8-4a6e-97a6-7665c822c57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-heading-2263&quot;)</value>
      <webElementGuid>9e572a4c-fb92-4bc9-9318-2437221b2717</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='component-heading-2263']</value>
      <webElementGuid>229b7095-ba5e-4709-9570-37b3141398c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-stripe-764']/div/h1</value>
      <webElementGuid>a947e049-f298-47d6-9acd-89f13c017290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[1]/following::h1[1]</value>
      <webElementGuid>cee0ddc1-2e27-446e-86f3-c67326dfca08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sustainability and ESG'])[1]/following::h1[1]</value>
      <webElementGuid>8067f799-d7d2-492d-84e7-c302eee0b4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Place an Order'])[1]/preceding::h1[1]</value>
      <webElementGuid>eb08644c-3fb8-43bf-8828-48e8535d42bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fluorescent Lamps'])[1]/preceding::h1[1]</value>
      <webElementGuid>647c4428-5a33-4797-bee7-16de0dfe79ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pack Back: How It Works']/parent::*</value>
      <webElementGuid>d6e46b89-9f31-46bc-8fd0-cf7ae8581dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>483461bc-31a2-4eb2-8d8b-9c469e12eaea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'component-heading-2263' and (text() = 'Pack Back: How It Works' or . = 'Pack Back: How It Works')]</value>
      <webElementGuid>47c49a65-3113-4322-80c9-ca088936423e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
