<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_A</name>
   <tag></tag>
   <elementGuidId>b53b9df8-8e85-482b-a0a3-0fdda7bf3253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='A']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#A</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>24f0e45c-1238-4ef5-a860-8b55d9a39578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabColor tdn</value>
      <webElementGuid>270c22c3-688c-4540-a7b3-a7ca013fdb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>A</value>
      <webElementGuid>3c54e6c0-d234-4b48-bd89-84139350de9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> A </value>
      <webElementGuid>2594d361-3f50-4cb7-8573-e41178b74bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;A&quot;)</value>
      <webElementGuid>1dab09d1-df7e-4ccc-9c30-572d6880c1ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='A']</value>
      <webElementGuid>de47d637-bc18-4b82-90ee-8d94130a9739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='idBody']/ngb-modal-window/div/div/app-cus-search/div/div[2]/app-cus-search-tabs/div[2]/div/div/drag-scroll/div/ul/li/a</value>
      <webElementGuid>5fb480a6-e79b-4f53-b321-07d3783dd189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'A')]</value>
      <webElementGuid>0d2be10a-90f4-479d-bf26-5f30c7935b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Name/ID'])[1]/following::a[2]</value>
      <webElementGuid>a73e6a48-59b6-40fc-8d17-f4aaeee49e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Customer'])[1]/following::a[2]</value>
      <webElementGuid>7ed53cff-97b9-456c-89fe-88cf71e5ca84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B'])[1]/preceding::a[1]</value>
      <webElementGuid>8160e65c-e283-4937-b51a-4758c628c788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C'])[1]/preceding::a[2]</value>
      <webElementGuid>edf7ca44-886f-4212-b82a-74b7d54cc8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='A']/parent::*</value>
      <webElementGuid>43f471be-b5f7-44b6-b644-f3b07cfe8ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//drag-scroll/div/ul/li/a</value>
      <webElementGuid>fe83a008-abaf-442a-83fb-c173e71e1617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'A' and (text() = ' A ' or . = ' A ')]</value>
      <webElementGuid>97686e43-ae4c-4a1c-ac92-b760c36daec5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
