<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer NameID_form-control form-con_0977f5</name>
   <tag></tag>
   <elementGuidId>f07c4062-3285-4302-b7ce-eb4c51c260be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[14]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.form-control-sm.pl5.pr5.ng-untouched.ng-valid.ng-dirty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2394f288-abaa-496c-b7ba-0fc61d1a36de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8bcbf69e-70fe-49f0-a73e-deb184c43178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm pl5 pr5 ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>6acbb6a7-7d20-4b5b-8b00-9f6ede6c8547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idBody&quot;)/ngb-modal-window[@class=&quot;d-block modal profile-modal fade show&quot;]/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/app-cus-search[1]/div[@class=&quot;modal-content mt-50 custom-modal custom-toaster-modal&quot;]/div[@class=&quot;modal-body&quot;]/app-cus-search-tabs[1]/div[@class=&quot;row mg10&quot;]/div[@class=&quot;col-md-5&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-7&quot;]/input[@class=&quot;form-control form-control-sm pl5 pr5 ng-untouched ng-valid ng-dirty&quot;]</value>
      <webElementGuid>258bb11b-faf1-4b59-840b-db1f5f5b4f07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[14]</value>
      <webElementGuid>ff5e4fda-8435-431c-aa12-add35331fc40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='idBody']/ngb-modal-window/div/div/app-cus-search/div/div[2]/app-cus-search-tabs/div/div/div/div[2]/input</value>
      <webElementGuid>3b06e4dd-9f97-4dd4-a061-0bd5a7b479d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-cus-search-tabs/div/div/div/div[2]/input</value>
      <webElementGuid>7b69a843-f001-4b1f-9887-8a63fa0a4b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>c9a3d6d3-0320-423f-889c-41e5e274992a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
