<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Florida 33675_checkbox-custom positio_b3f0da</name>
   <tag></tag>
   <elementGuidId>9299d9c9-33a7-4a7c-a36b-32628db7acf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.checkbox-custom.position-absolute.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3da7e724-1752-46fe-866d-d0069d05edfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2b1cd7ea-c233-438d-b344-bcdd278850a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>e70dd091-c6cb-407d-9c9e-3ee0d2f1be93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-custom position-absolute ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3d2a566f-e8e1-4017-b3d5-e7a13b08478d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightcontent&quot;)/app-pack-back-payment[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper ng-star-inserted&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;ptt00 pickup-part row m0&quot;]/div[@class=&quot;e-learning-body&quot;]/div[@class=&quot;row d-flex confirmNote&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;position-relative&quot;]/input[@class=&quot;checkbox-custom position-absolute ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>9395729c-6f6f-4083-ad9c-489e8b48b5a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[4]</value>
      <webElementGuid>834c488b-2b13-4b2f-a364-268561a9e868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-pack-back-payment/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>acc2c95e-3f27-44de-b621-59afab76340f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>4d8c8839-ffb9-4bd7-94e9-6cd40994ba56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>79190dd8-991c-4889-a989-e19aeebd2e1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
