<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Order ID_form-control form-control-sm_90fb7f</name>
   <tag></tag>
   <elementGuidId>e5ffcbeb-5ebb-4a40-88a3-a8427963ed82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.form-control-sm.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7f7b8a6-2040-40ce-a7f3-ddfb59456905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b1c07cd5-9ec0-4a07-b7a9-4658ef6a32b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>0000000000</value>
      <webElementGuid>ded0457b-e81e-4d29-b92a-191315d47641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>34336b74-cd30-4a24-a13b-72710b22935c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightcontent&quot;)/app-order-track[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ptt00 mh900 pickup-part m20&quot;]/div[@class=&quot;row m20&quot;]/div[@class=&quot;col-md-3 col-sm-4 mb-3 form-group&quot;]/input[@class=&quot;form-control form-control-sm ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>116169d2-ecd9-40f0-8c74-618eeecbaa7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>bc2f68b1-60f7-48d5-9e76-cab87fa2aa2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-order-track/div[2]/div/div[2]/input</value>
      <webElementGuid>436b801f-927b-4750-94e0-1db76950f468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a9c32092-6618-4d4e-a91b-48c05c96af7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>c1a6e664-1d1c-46e4-8c9d-b79ba810e1f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
