<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Purchase Order_purOrder</name>
   <tag></tag>
   <elementGuidId>2e1354f4-182c-469b-aeea-e32bf98cc772</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='purOrder']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#purOrder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cafb48e2-0b9d-4a69-b30a-65067d3dca28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb01b61a-51b6-4ec7-9a69-e8a9066e2cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>9af76b0d-4180-4c0b-aa5c-7dfc0e8bba1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>purchase_order</value>
      <webElementGuid>fcfcf6f5-5ed9-4744-9043-3a3df038cff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>purOrder</value>
      <webElementGuid>b11d9dff-e039-4f64-8349-9a6047ddf015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>purOrder</value>
      <webElementGuid>b7519c61-3494-489a-b478-f57722e71393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-md ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>25c9c19d-a340-475c-bc15-7679a33ae1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;purOrder&quot;)</value>
      <webElementGuid>1649b97e-8bac-48cf-aa18-7eb9d04cce53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='purOrder']</value>
      <webElementGuid>2c21de99-1fb4-45d6-b706-818e7c6b30f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-checkout/div/app-useraddress/div/div/div/div/div/div/form/div/div/div[5]/div[2]/div/input</value>
      <webElementGuid>7c3faa64-0af6-415b-af61-587ec5b24487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>dca63072-1b0c-4c1b-b3b9-88eff61486a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'purOrder' and @name = 'purOrder']</value>
      <webElementGuid>76a2de97-1fc5-417a-9f26-f0c740c8d884</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
