<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Attention_Ship_attention</name>
   <tag></tag>
   <elementGuidId>344866c5-8bfe-41f5-b895-a7cfbae9c8d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Ship_attention']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Ship_attention</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0fd9a3d-3a46-416c-a7a6-e3cbefddc501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>014e729e-5fb6-4783-a9fc-4c9ff5ea4691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>0a12c180-bb09-4a6c-aee7-0fb4ee398023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>Ship_attention</value>
      <webElementGuid>e707cc32-05ba-4666-a62b-7b938f101292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Ship_attention</value>
      <webElementGuid>f819bca0-81a5-4985-b30b-c3c4a7351eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Ship_attention</value>
      <webElementGuid>740e75dc-8b5d-47af-ad9d-c8346fdcf8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-md ng-pristine ng-invalid has-error ng-touched</value>
      <webElementGuid>87965b69-f6e6-4180-a6fb-c4d1c891521e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Ship_attention&quot;)</value>
      <webElementGuid>84dc182c-206a-49a2-b40a-85997c7a92c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Ship_attention']</value>
      <webElementGuid>f0421754-c407-4b81-a955-a1274b380de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-checkout/div/app-useraddress/div/div/div/div/div/div/form/div[3]/div[2]/div[3]/div[2]/input</value>
      <webElementGuid>7984cbee-faec-465a-845a-9886c62c00f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/input</value>
      <webElementGuid>109e5395-0bb3-4ba8-9ebb-9a0ac56b97e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Ship_attention' and @name = 'Ship_attention']</value>
      <webElementGuid>2415f841-14c2-465b-9c85-97126f2f4e34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
