<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_0 - Standard Customer Billing</name>
   <tag></tag>
   <elementGuidId>0ec0634c-e43f-499e-895a-70987e05a4df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='billingProject']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billingProject</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fb80cf36-9e18-4d4c-8756-85a47c10fae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5fd51538-c601-4de8-a204-bcdbd5ae3922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a005a227-8194-4e72-8086-ec18922ecefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>billingProject</value>
      <webElementGuid>c5a93958-acff-4ff3-8ad3-9d27c1a490b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingProject</value>
      <webElementGuid>7cffc2a2-ecd9-4437-8571-82718c9702f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingProject</value>
      <webElementGuid>82e536aa-192a-4b09-b0cb-d789df144385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-select-md mgwidth105_per ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>ceb30a35-db78-4053-981c-a0c290b439b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 0 - Standard Customer Billing </value>
      <webElementGuid>f404ae05-317b-481f-aa17-6376c7a52e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingProject&quot;)</value>
      <webElementGuid>1acd0bb7-d9fd-4512-b8fb-9d0e2230edb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='billingProject']</value>
      <webElementGuid>6b5e6be7-a27e-4bff-883b-ef923bb36281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-checkout/div/app-useraddress/div/div/div/div/div/div/form/div/div/div[2]/div[2]/div[2]/select</value>
      <webElementGuid>a5910588-fc11-4364-bc21-f4577ea6b9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Project:'])[1]/following::select[1]</value>
      <webElementGuid>34ce12e1-d292-46d0-abba-98c633219d20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer:'])[1]/following::select[1]</value>
      <webElementGuid>de27350b-762e-4d20-a459-6cf6e35dd95d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name:'])[1]/preceding::select[1]</value>
      <webElementGuid>5aac3470-f356-419f-8ff9-f90f9e3f34ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name:'])[1]/preceding::select[1]</value>
      <webElementGuid>ca705716-a7ba-4cd9-86c4-9ed8cc35a665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>52f55b59-ee96-46ed-9143-0a5da4817ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'billingProject' and @name = 'billingProject' and (text() = ' 0 - Standard Customer Billing ' or . = ' 0 - Standard Customer Billing ')]</value>
      <webElementGuid>13241079-479b-4900-9d04-61701005b78c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
