<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Username</name>
   <tag></tag>
   <elementGuidId>38eff650-7ac1-409b-b81b-33aea1574f83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='idBody']/app-root/app-forgot-password/form/div/div/div[3]/div[2]/div/mat-form-field/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c129-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c9018a93-7609-4406-b03e-219f549cc681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix ng-tns-c129-3</value>
      <webElementGuid>de75d168-bb81-4bf0-b3c8-036e1b72470d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>2de4a80f-ec31-4611-b2a1-82056798de54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idBody&quot;)/app-root[1]/app-forgot-password[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;form-horizontal mb0 ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;login_bg pos-relative&quot;]/div[@class=&quot;delighted-login scrollbar&quot;]/div[@class=&quot;form-section text-center packbackform&quot;]/div[@class=&quot;mb10 ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/mat-form-field[@class=&quot;mat-form-field ng-tns-c129-3 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-has-label mat-form-field-hide-placeholder ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c129-3&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c129-3&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c129-3&quot;]</value>
      <webElementGuid>f470acc9-b20f-41e5-81f6-871e62df2187</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='idBody']/app-root/app-forgot-password/form/div/div/div[3]/div[2]/div/mat-form-field/div/div/div[2]</value>
      <webElementGuid>164c9b1e-9836-44aa-a07f-b28a39e78c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter the Username you use to sign in to COR'])[1]/following::div[5]</value>
      <webElementGuid>049fe51c-8041-472c-b2d8-6d84b0952131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('I don', &quot;'&quot;, 't know my username')])[1]/following::div[6]</value>
      <webElementGuid>4bb448e9-58bd-4d4d-acc6-bf32f7b2ba3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[6]</value>
      <webElementGuid>226bd0c7-4fc8-40d9-a070-f5edd6d7be2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field/div/div/div[2]</value>
      <webElementGuid>268245e9-fb0d-4f05-8588-13a6077d65be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Username' or . = 'Username')]</value>
      <webElementGuid>9f055509-1979-4c94-83a5-58b3d6e67889</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
