<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Anand Manickam</name>
   <tag></tag>
   <elementGuidId>23737770-84cb-40c9-9e9e-994d35149273</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.d-inline-flex.align-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='themeH']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46905ec2-dc53-427a-b52a-2bf26ec41ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>febecd0a-febe-4a6a-b642-4c1570ab3fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-inline-flex align-center</value>
      <webElementGuid>c42dea26-eee1-4c28-a4e4-ff18b81d8f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip-2</value>
      <webElementGuid>4e3cee2e-1f8d-4abd-99e6-fc91c5bcc633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anand Manickam</value>
      <webElementGuid>c0727b78-090f-437b-8315-45fe0e7b2c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;themeH&quot;)/div[@class=&quot;d-inline-flex align-center&quot;]</value>
      <webElementGuid>910e4a1b-0f9a-4fad-91a3-ec651696824e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='themeH']/div[2]</value>
      <webElementGuid>6e64b91d-0bbf-49b8-bd75-03650cf52ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome'])[1]/following::div[1]</value>
      <webElementGuid>10292404-cbc9-4ed2-a9b7-e83716e79a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(800) 592-5489'])[1]/following::div[14]</value>
      <webElementGuid>9fb70af7-2b4f-4bd7-bde6-00b2365de54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anand Manickam'])[2]/preceding::div[2]</value>
      <webElementGuid>ac9ce166-7dba-4e43-bb37-aed8514017f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-pack-back-sidemenu/div/div/div[2]</value>
      <webElementGuid>60b70d22-f6b3-41f2-96b9-d8a13e9d954a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Anand Manickam' or . = 'Anand Manickam')]</value>
      <webElementGuid>4089a841-a9c2-4e50-b604-c7287de33a41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
