<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sorry, we couldnt find any results matc_468a4e</name>
   <tag></tag>
   <elementGuidId>2840a5fb-c94d-4ce3-af87-c7bf3f74c7b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-container']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ng-tns-c56-4.toast-message.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>88cf2d2b-61f9-4850-9202-37e599b17216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alertdialog</value>
      <webElementGuid>ba71815f-066b-482c-a6ad-718e6990b14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>a437456a-c3f2-4e30-86c8-37b0b04683ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c56-4 toast-message ng-star-inserted</value>
      <webElementGuid>abb14326-fff0-45c3-adff-4fd66e145bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Sorry, we couldn't find any results matching username Ramya. Please contact your Customer Service Specialist for additional details.</value>
      <webElementGuid>817d43a6-98e3-4cdc-aa77-1b4d96f27478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sorry, we couldn't find any results matching username Ramya. Please contact your Customer Service Specialist for additional details. </value>
      <webElementGuid>f019a8e6-5edc-4c2e-9cfe-23f9f65860cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-container&quot;)/div[@class=&quot;ng-tns-c56-4 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-error&quot;]/div[@class=&quot;ng-tns-c56-4 toast-message ng-star-inserted&quot;]</value>
      <webElementGuid>166e13db-6f04-49cb-87f8-707e08d5525b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-container']/div/div</value>
      <webElementGuid>d8578e0a-2e92-427e-a537-5a7bc8feae7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::div[6]</value>
      <webElementGuid>197d79bd-12ec-4a69-b5e1-4eec0bf6e39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::div[6]</value>
      <webElementGuid>bbdec88f-9a23-4838-af6f-f2cd8a00be9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>d1a9fc67-4a75-4c0d-af57-a8b1fe7eeae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot; Sorry, we couldn&quot; , &quot;'&quot; , &quot;t find any results matching username Ramya. Please contact your Customer Service Specialist for additional details. &quot;) or . = concat(&quot; Sorry, we couldn&quot; , &quot;'&quot; , &quot;t find any results matching username Ramya. Please contact your Customer Service Specialist for additional details. &quot;))]</value>
      <webElementGuid>78e2e6da-e910-471d-9f23-a1fa3da20e03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
