<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_(800) 592-5489_mainImg</name>
   <tag></tag>
   <elementGuidId>5d7c588c-ba31-412e-91e7-42c3ff79a9c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainImg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='mainImg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>634a700e-bc8f-4f05-a4fd-cf9225ce3766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainImg</value>
      <webElementGuid>af0de802-633f-4680-8020-f4e5543df038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./assets/images/Logout.svg</value>
      <webElementGuid>0e347eda-a17b-4a10-85a9-31f63d1e4215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logout</value>
      <webElementGuid>f77d2d19-41f6-403c-915d-1bee9673b75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>75%</value>
      <webElementGuid>20a1ca62-cc60-4b5a-8da7-1d2b6380bbd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>75%</value>
      <webElementGuid>12a8a850-4f7b-4814-8590-4b0648bffe5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placement</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>cc9629e7-432e-4fc7-9c63-de82fa9f58ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logout-icn</value>
      <webElementGuid>876bd679-2a96-42ee-9dfb-98363962f5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip-3</value>
      <webElementGuid>f7d2f0da-ce08-4853-9b2a-a4dd5561268d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainImg&quot;)</value>
      <webElementGuid>b2a88263-93b9-4566-899d-c0a664260fe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='mainImg']</value>
      <webElementGuid>6177bcf2-c3fa-445d-b76b-29e3508b95fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='idBody']/app-root/app-pack-back-main/app-pack-back-header/header/div/div/div/div[2]/ul[2]/li[6]/div/a/img</value>
      <webElementGuid>60655f5c-65d5-47f9-994e-5d0be8f9774d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logout']</value>
      <webElementGuid>74229c51-52ed-424b-a62f-e00c528e5b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/a/img</value>
      <webElementGuid>15e06ad8-6e00-4ec8-b3a7-011d75d49f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'mainImg' and @src = './assets/images/Logout.svg' and @alt = 'logout']</value>
      <webElementGuid>6f05f416-d8a8-48e8-8233-d73ed754ad0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
