<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(I don, , t know my password)_F_7493be</name>
   <tag></tag>
   <elementGuidId>985e7d6c-e054-4ed2-9bc2-3ea8e53b3f31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='forgotUsername']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#forgotUsername</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9ad54f5-bb0c-435d-8126-562a85f8dc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3f97fef7-61d4-46fa-a285-5ed2e3b05883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>forgotUsername</value>
      <webElementGuid>9f056c8f-d1f3-4977-80d1-935ab0a89024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ForgotType</value>
      <webElementGuid>c9325418-1ce1-42cf-8e5c-963c7985102c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>user</value>
      <webElementGuid>33b0500e-034b-49d3-baa0-e151b61941f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-un ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>e2370fc7-043c-4f78-89e5-d6c520c80c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgotUsername&quot;)</value>
      <webElementGuid>46454836-ca57-4b88-aeda-6f6c57c93076</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='forgotUsername']</value>
      <webElementGuid>84eee88a-a7cd-4333-af14-89d9f597a499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='idBody']/app-root/app-forgot-password/form/div/div/div[3]/div/div[3]/input</value>
      <webElementGuid>8f892188-754a-44d7-9af8-44668950ae6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>86a98e02-98f1-40e3-8165-64c6d95af8e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'forgotUsername' and @name = 'ForgotType']</value>
      <webElementGuid>4860040b-0f04-4a02-bf7a-bcdcc353b1e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
