<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Quantity_fa fa-plus qtyIcon</name>
   <tag></tag>
   <elementGuidId>e4e1ffed-89b5-4dbf-aa5b-cb9680c4b76d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='rightcontent']/app-productlist/div/div[3]/div/div/div/div/div/div[4]/div/button[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-plus.qtyIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>64fe6c46-ef1c-4bd2-b23b-ad71eb25e4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus qtyIcon</value>
      <webElementGuid>923a5390-ce90-41c4-9f55-f6464c7ae8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightcontent&quot;)/app-productlist[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;ptt00 mh900 pickup-part pack-back-part ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 col-sm-12 col-lg-3 col-xl-3 ng-star-inserted&quot;]/div[@class=&quot;productCard&quot;]/div[@class=&quot;card-body prd_details&quot;]/div[@class=&quot;d-inline-flex marginList&quot;]/div[@class=&quot;wrapper_btn&quot;]/button[@class=&quot;plusminus&quot;]/span[@class=&quot;fa fa-plus qtyIcon&quot;]</value>
      <webElementGuid>37422f62-77a8-45d2-8e6e-4a1366ea9e3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-productlist/div/div[3]/div/div/div/div/div/div[4]/div/button[2]/span</value>
      <webElementGuid>f51b9d5f-563d-4233-a505-62d62cda0017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>89aabf4b-24b3-4c7a-8cbb-f2d633718c51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
