<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Leaflet   OpenStreetMap contributors</name>
   <tag></tag>
   <elementGuidId>35e54d0b-ea5f-49d9-b8d0-6b464c22ccec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leaflet-map-view-location-search-block-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#leaflet-map-view-location-search-block-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e034098c-72f1-4f99-af37-2b2536463c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leaflet-map-view-location-search-block-1</value>
      <webElementGuid>c7ebb2fe-28a7-4faf-89b4-01766851f30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-container leaflet-touch leaflet-retina leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom</value>
      <webElementGuid>d751adc9-3d99-4ae7-8fa4-c174b3e87d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>81000665-9f5c-4f21-8075-acfc0aa90a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+− Leaflet | © OpenStreetMap contributors</value>
      <webElementGuid>30f35f41-9ed0-4eb2-8734-4074e1d385c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leaflet-map-view-location-search-block-1&quot;)</value>
      <webElementGuid>ad7eaf7d-c994-4113-bde8-3812781b82d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='leaflet-map-view-location-search-block-1']</value>
      <webElementGuid>efc34985-b966-4c4b-a5d5-6d4db9a16a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='special-view-54']/div/div/div/div/div</value>
      <webElementGuid>362a0e10-7fa8-4637-951d-f9ea7f884759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(800) 899-4672'])[1]/following::div[18]</value>
      <webElementGuid>3da21cb7-5a8a-427e-8a59-e6c5e587d495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::div[19]</value>
      <webElementGuid>400ae56f-a0af-496c-972c-61b469b39e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>66f4b661-e59c-4be9-9a6f-6b8355b146ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'leaflet-map-view-location-search-block-1' and (text() = '+− Leaflet | © OpenStreetMap contributors' or . = '+− Leaflet | © OpenStreetMap contributors')]</value>
      <webElementGuid>1c0caf40-ec8f-4b52-9ffe-081d81474ea9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
