<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Location_field_geocode_proximi_d80d32</name>
   <tag></tag>
   <elementGuidId>6c4a4aa0-d6e5-40a1-b08d-1fdb2020c9a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-field-geocode-proximity-source-configuration-origin-address--3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58d31ce4-40e2-4794-a7e6-e482b41effcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>address-input form-text ui-autocomplete-input form-autocomplete</value>
      <webElementGuid>0a678125-04c3-4a2d-9a27-0092514053be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-field-geocode-proximity-source-configuration-origin-address</value>
      <webElementGuid>45e90e9f-2263-4e4d-88af-e769ba0761b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97875059-9670-45b2-aafc-a577fbed33b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-field-geocode-proximity-source-configuration-origin-address--3</value>
      <webElementGuid>4a50f7e0-27a0-4e13-b793-814b12e6ca2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_geocode_proximity[source_configuration][origin_address]</value>
      <webElementGuid>00c655da-fb69-4a26-aad0-d38c96269d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>a6fad64c-d19e-4e88-88ba-9e8065af705e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>f13fdbf6-bcae-4f33-bf08-4574e1dbc7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City, State, Zip</value>
      <webElementGuid>dff98f79-ff63-4d68-885a-5931fc97cd6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>autocomplete-enabled</value>
      <webElementGuid>6805f802-4996-43c9-8027-fa2a5890eb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>05b29f80-c154-44f7-9632-70ffeb9b98c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-field-geocode-proximity-source-configuration-origin-address--3&quot;)</value>
      <webElementGuid>2de2207a-314f-4d1c-8b0f-28faaa8b8398</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-field-geocode-proximity-source-configuration-origin-address--3']</value>
      <webElementGuid>06b76993-eb70-4480-90d1-92edc0d9161b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-field-geocode-proximity-source-configuration--3']/div/input</value>
      <webElementGuid>2f31253c-d919-4e82-92f2-e3c2f008d0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>6afa6989-adfb-4421-942d-28c96ea56165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'edit-field-geocode-proximity-source-configuration-origin-address--3' and @name = 'field_geocode_proximity[source_configuration][origin_address]' and @placeholder = 'City, State, Zip']</value>
      <webElementGuid>5920318c-13d6-4340-aad7-c02c8ab8e2eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
