<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_US Ecology Tilbury22153 King  Whittle R_b6353b</name>
   <tag></tag>
   <elementGuidId>39dfc86b-d5c1-4460-94f6-04beca6b8452</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='section-column-151']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#section-column-151</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>28413c4f-f640-4786-ba67-cae63718c885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>eck-entity entity-type-section entity-bundle-column entity--section-column view-mode--default entity--section-column-default entity-column-151 from-parent--field-columns display--flex flex-direction--column contains-component--special background--section-column-151 has-field-components justify-content--flex-start doNotRevealOnScroll flex--1 padding-horizontal--2 text-align--left</value>
      <webElementGuid>13bb5cd3-7f4d-4f0b-9507-9c46de09b4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>section-column-151</value>
      <webElementGuid>d54045cc-6956-43a6-aa6b-bcf311546f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-animation</name>
      <type>Main</type>
      <value>slideInUp</value>
      <webElementGuid>ec582ebc-056f-44bc-8e1f-88bb7a4b159c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>US Ecology Tilbury22153 King &amp; Whittle Rd.TilburyONN0P2L0CanadaUS Ecology Sarnia145 Scott Rd.SarniaONN7T7V8Canada</value>
      <webElementGuid>314c952c-926e-4aa8-b21e-81a9719a4c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-column-151&quot;)</value>
      <webElementGuid>707594ab-49cd-436a-8f87-15d5bc56a15b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='section-column-151']</value>
      <webElementGuid>c284533e-da37-497a-9e1c-c8a7ade835ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='component-layout-593']/div[2]</value>
      <webElementGuid>3119ae64-f1fb-4920-8c2f-84136138bafd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OpenStreetMap'])[1]/following::div[1]</value>
      <webElementGuid>41be5b2c-3a28-455d-89ec-1c65bfeab622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaflet'])[1]/following::div[1]</value>
      <webElementGuid>a78e4102-0ced-4b6d-b2b8-71a45be7ff5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div/div/div[2]</value>
      <webElementGuid>4e443e38-2e58-472d-8d06-9e3ab0965f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'section-column-151' and (text() = 'US Ecology Tilbury22153 King &amp; Whittle Rd.TilburyONN0P2L0CanadaUS Ecology Sarnia145 Scott Rd.SarniaONN7T7V8Canada' or . = 'US Ecology Tilbury22153 King &amp; Whittle Rd.TilburyONN0P2L0CanadaUS Ecology Sarnia145 Scott Rd.SarniaONN7T7V8Canada')]</value>
      <webElementGuid>235e6ace-836f-4e08-a9fb-60dd8b6be413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
