<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_US Ecology Tilbury22153 King  Whittle R_b6353b_1</name>
   <tag></tag>
   <elementGuidId>3b29e425-99b5-4ce7-8be9-1b2103aeaae0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='special-view-57']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.border--1px-solid.padding-horizontal--4.padding-vertical--4.overflow-y--auto.max-height--400px.view.view-location-search.view-id-location-search.view-display-id-block-3.js-view-dom-id-d7bc7b53ede39eca976eec1244c12b8a92fb3e758f727b150d60f2ccc24cd361</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>de5b4d95-f2bc-4d05-96ba-5d04098054b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border--1px-solid padding-horizontal--4 padding-vertical--4 overflow-y--auto max-height--400px view view-location-search view-id-location-search view-display-id-block-3 js-view-dom-id-d7bc7b53ede39eca976eec1244c12b8a92fb3e758f727b150d60f2ccc24cd361</value>
      <webElementGuid>ca73e3da-f2c1-416f-817a-1379c661e732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>US Ecology Tilbury22153 King &amp; Whittle Rd.TilburyONN0P2L0CanadaUS Ecology Sarnia145 Scott Rd.SarniaONN7T7V8Canada</value>
      <webElementGuid>db31702e-303e-44c4-8ea4-3ee51adeaf19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;special-view-57&quot;)/div[@class=&quot;field field-name--field-view field-type--viewsreference field-label--hidden field-formatter--viewsreference-formatter&quot;]/div[@class=&quot;views-element-container&quot;]/div[@class=&quot;border--1px-solid padding-horizontal--4 padding-vertical--4 overflow-y--auto max-height--400px view view-location-search view-id-location-search view-display-id-block-3 js-view-dom-id-d7bc7b53ede39eca976eec1244c12b8a92fb3e758f727b150d60f2ccc24cd361&quot;]</value>
      <webElementGuid>5da3a7b7-5602-4cf7-a354-56c070ad2092</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='special-view-57']/div/div/div</value>
      <webElementGuid>9c7184f0-cdf4-4d11-b06f-5b0220ea1783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OpenStreetMap'])[1]/following::div[6]</value>
      <webElementGuid>ff1a9d0e-0d49-4079-847b-b48008e03cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaflet'])[1]/following::div[6]</value>
      <webElementGuid>2ad801c7-d6e4-483e-9d76-ec712d0d0bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div</value>
      <webElementGuid>227ad9d6-1983-4e20-9fbf-171f448b6ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'US Ecology Tilbury22153 King &amp; Whittle Rd.TilburyONN0P2L0CanadaUS Ecology Sarnia145 Scott Rd.SarniaONN7T7V8Canada' or . = 'US Ecology Tilbury22153 King &amp; Whittle Rd.TilburyONN0P2L0CanadaUS Ecology Sarnia145 Scott Rd.SarniaONN7T7V8Canada')]</value>
      <webElementGuid>fd0bebf4-4324-4c14-bddb-3b3bfd6dc6f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
