<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_United States</name>
   <tag></tag>
   <elementGuidId>e6aa82fb-d4d3-4fb7-b223-c8d4aee5bdcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit_field_address_country_code__3_chosen']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.chosen-single > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f25cce2a-4112-4400-bc8c-7248101015db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>United States</value>
      <webElementGuid>99e6ebc5-fd0d-49cf-b246-27bc2a90067c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_field_address_country_code__3_chosen&quot;)/a[@class=&quot;chosen-single&quot;]/span[1]</value>
      <webElementGuid>bdb213bd-cc3e-4dd4-84bc-3ca2970561ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit_field_address_country_code__3_chosen']/a/span</value>
      <webElementGuid>5e468061-2406-413a-868b-9973ad945a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Country'])[1]/following::span[1]</value>
      <webElementGuid>954acb85-1cde-4e0a-ac07-5708e089b291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='US Ecology Locations'])[1]/following::span[1]</value>
      <webElementGuid>8b5b904f-98e8-4d1c-bfa3-50886db81825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[3]/preceding::span[1]</value>
      <webElementGuid>9ffb8150-0dbe-4eef-bb21-e06e8d055cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Canada'])[2]/preceding::span[1]</value>
      <webElementGuid>7b6788db-e07c-4962-af64-2c08a4c91379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>ba09c0d5-11e2-4750-99c4-9629062f275d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'United States' or . = 'United States')]</value>
      <webElementGuid>a620be50-b362-46bb-a73c-15099d10ec88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
