<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Filter by Service_chosen-choices</name>
   <tag></tag>
   <elementGuidId>163431d9-4e49-4e47-9825-b6d2356ba5fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit_service_cats__3_chosen']/ul</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.chosen-choices</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>48c00d47-3a35-46be-9e59-e0628ab28b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chosen-choices</value>
      <webElementGuid>54145583-3f08-4449-b238-fbe9fe8003f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_service_cats__3_chosen&quot;)/ul[@class=&quot;chosen-choices&quot;]</value>
      <webElementGuid>5f7d7f97-1fcc-4629-ab44-e49f1977b38b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit_service_cats__3_chosen']/ul</value>
      <webElementGuid>cea5a4e1-8cc3-44d8-b77f-a4892396615e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter by Service'])[1]/following::ul[1]</value>
      <webElementGuid>3ec4b9a2-1dd4-45ac-aa4a-a635fb32390f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Location'])[1]/following::ul[1]</value>
      <webElementGuid>b7f7ac68-588e-4072-8c36-12231b43b644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emergency Response Services'])[3]/preceding::ul[1]</value>
      <webElementGuid>de2a30f6-3ca5-4a3c-a2de-b590d7519b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Field Services'])[3]/preceding::ul[1]</value>
      <webElementGuid>8e248105-741e-4481-81fd-a20195cdc8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul</value>
      <webElementGuid>d11a8f59-728f-4be6-a1bf-3f8c177c15a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
