<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete</name>
   <tag></tag>
   <elementGuidId>68007e4d-482b-4d05-a26b-c1317e0e3c04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='idBody']/ngb-modal-window/div/div/app-remove-row/div/div[2]/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.white.btn.btn-sm.btn-danger.ml-0.mtr10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9de8c7a1-e9cd-44f0-890f-07709097448d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>white btn btn-sm btn-danger ml-0 mtr10</value>
      <webElementGuid>d34905cc-aa47-44c1-a7f4-c79a7d0d0a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>97f6ed2d-4b7d-4184-a5fa-15bc2a0ec952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idBody&quot;)/ngb-modal-window[@class=&quot;custom-toaster-modal d-block logoutPop modal fade show&quot;]/div[@class=&quot;modal-dialog modal-sm&quot;]/div[@class=&quot;modal-content&quot;]/app-remove-row[1]/div[@class=&quot;getlookuppopup&quot;]/div[@class=&quot;modal-body&quot;]/div[1]/div[@class=&quot;text-right&quot;]/button[@class=&quot;white btn btn-sm btn-danger ml-0 mtr10&quot;]</value>
      <webElementGuid>2ef00146-78ff-4ca9-abf3-9b538b6e58f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='idBody']/ngb-modal-window/div/div/app-remove-row/div/div[2]/div/div/button</value>
      <webElementGuid>a1513397-9ec6-493c-b0cf-640a04634b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Confirmation'])[1]/following::button[1]</value>
      <webElementGuid>a7906c2a-0fbc-45fe-8757-79093b969cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select User to Impersonate'])[1]/following::button[1]</value>
      <webElementGuid>c5fc4b6f-d72a-450c-8697-03397c94ca54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>ee81c2c9-ecd5-44f6-93fe-9781f737a9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete']/parent::*</value>
      <webElementGuid>e14535b6-2320-4f88-b731-64e4ed5579eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/button</value>
      <webElementGuid>9222db88-f196-41ef-88ba-3577a79af36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>8f923bc0-45a3-4134-ad90-1fc6aaf1dd20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
