<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_The Republic Services Pack Back Recycli_e978c0</name>
   <tag></tag>
   <elementGuidId>d647f4b0-6371-415b-8a57-5ce565b2c236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='idBody']/ngb-modal-window/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal-body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>26d0e573-0df1-4f3c-a18f-1fdbb1fec954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body</value>
      <webElementGuid>6b081a10-4b4f-484f-9ded-06632a4e6ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Republic Services Pack Back Recycling Program offers auto-replenishment to help simplify future orders.When placing your initial order, simply select the 'auto-replenishment' option and upon receipt of your materials for recycling, a new order will automatically be billed to your customer account or credit card and shipped to you.</value>
      <webElementGuid>74466059-ccab-47ac-8cd5-d434a0bcc528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idBody&quot;)/ngb-modal-window[@class=&quot;custom-toaster-modal d-block modal modal-dialog-centered fade show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;mt-42vh getlookuppopup&quot;]/div[@class=&quot;modal-body&quot;]</value>
      <webElementGuid>ea439459-20d6-4ff1-b72a-243110835fef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='idBody']/ngb-modal-window/div/div/div/div[2]</value>
      <webElementGuid>66c03a0e-6479-4873-8672-72b9fbab6274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pack Back Offers Auto-Replenishment'])[1]/following::div[1]</value>
      <webElementGuid>014966a0-db19-4a2a-9445-ec5ca3ddf691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select User to Impersonate'])[1]/following::div[10]</value>
      <webElementGuid>c3acc581-e71c-42c3-8aee-ea5afbb4755f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ngb-modal-window/div/div/div/div[2]</value>
      <webElementGuid>5aba968e-0b1a-43eb-aa3d-21c5d2cfcd7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;The Republic Services Pack Back Recycling Program offers auto-replenishment to help simplify future orders.When placing your initial order, simply select the &quot; , &quot;'&quot; , &quot;auto-replenishment&quot; , &quot;'&quot; , &quot; option and upon receipt of your materials for recycling, a new order will automatically be billed to your customer account or credit card and shipped to you.&quot;) or . = concat(&quot;The Republic Services Pack Back Recycling Program offers auto-replenishment to help simplify future orders.When placing your initial order, simply select the &quot; , &quot;'&quot; , &quot;auto-replenishment&quot; , &quot;'&quot; , &quot; option and upon receipt of your materials for recycling, a new order will automatically be billed to your customer account or credit card and shipped to you.&quot;))]</value>
      <webElementGuid>01131c30-acb4-437c-8afd-0dd3d425e494</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
