<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_fname</name>
   <tag></tag>
   <elementGuidId>cffcb9df-1e26-4b72-b015-361c7521c17f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df07965f-e6ed-4358-a959-601f5ca776c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>94a98553-b9e4-474d-81b5-34f1c467c36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d1a0c1cb-db5c-4170-976e-06155d39dcb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>contact_first_name</value>
      <webElementGuid>b04bd164-39b6-48d4-8516-70c089529ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fname</value>
      <webElementGuid>73d8d035-9d99-4ec7-a19f-19ee768f03cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fname</value>
      <webElementGuid>0e1a84f8-344f-4d81-b720-cd175ad1b651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-md ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>8e988f69-0aad-4482-9d1f-0eba2bcbb1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fname&quot;)</value>
      <webElementGuid>846cbc73-73e7-4e74-9e9e-f3e464bbe966</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fname']</value>
      <webElementGuid>7fedde18-f0a0-4a76-83a1-3cb1508e93cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-pack-back-register/div/div/div/div/div/div/div/form/div/div[3]/div/div/div[2]/input</value>
      <webElementGuid>1ec7d57b-7c4c-44bd-bbba-22b16037f965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1fefffea-0650-4ffb-b58a-e4879f37bd94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fname' and @name = 'fname']</value>
      <webElementGuid>aad923ba-06f7-4fd4-a367-80868ca8a13c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
