<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Attention_attension</name>
   <tag></tag>
   <elementGuidId>8067b7e1-ab69-4433-8ae3-c03f2c4c9910</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attension</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='attension']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54ecb93e-be5c-455f-ba35-43c4efdaabda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>306aa093-1577-431d-8b8c-b899c7b6909c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>78d3a36f-9cfc-4799-a020-758eb8faa39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>cust_attention_name</value>
      <webElementGuid>9684845d-20ee-44ab-a8f1-ff7526963f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attension</value>
      <webElementGuid>11290670-d1dc-4941-89bf-65901b8cd432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attension</value>
      <webElementGuid>60d95dc2-497f-4c43-800e-145264c4f1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-md ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>f3d49ee6-cc20-433e-96f0-ccdcaeea67a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attension&quot;)</value>
      <webElementGuid>4776a834-7e22-4dca-8497-c88c4cd44116</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='attension']</value>
      <webElementGuid>11b61d2c-ba9d-46a2-808d-ce6840215d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-pack-back-register/div/div/div/div/div/div/div/form/div[2]/div[3]/div/div[4]/div[2]/input</value>
      <webElementGuid>f3722fd2-d2e1-4076-b2d3-fdda3b6a3449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>5b34adc2-2ba3-4f6a-bc62-a193133f4d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'attension' and @name = 'attension']</value>
      <webElementGuid>bb3e1308-8108-4411-844b-cd6e5c5ee4d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
