<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_cusphone</name>
   <tag></tag>
   <elementGuidId>0b93a9f3-574d-499d-8c35-f0782be01ced</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cusphone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cusphone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb8cca38-f49d-4ad9-aa4a-789ae31f9c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0add3e9a-ae36-4964-b7ad-8a6d248e6c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>0681af52-03e0-4f0a-b951-df0471317d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>contact_phone</value>
      <webElementGuid>b0538a99-b8d5-4bd1-9c09-4165d753b1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cusphone</value>
      <webElementGuid>67d6f158-7951-468a-b36c-e9ca4ecc14e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cusphone</value>
      <webElementGuid>e0839a89-deca-4fa1-836b-4b4fa7fbc6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>(000) 000-0000</value>
      <webElementGuid>64f6168d-9314-46c6-8ceb-2390208b1de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-md ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6119423b-2396-4b4a-8cde-4524b4be4bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cusphone&quot;)</value>
      <webElementGuid>9aa45a39-38e4-4aff-b94e-c7db8837c1cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cusphone']</value>
      <webElementGuid>97d89686-5b6a-467c-8b85-d66d24f9e025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-pack-back-register/div/div/div/div/div/div/div/form/div/div[4]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>e1394d14-23c4-45d0-89b5-2c5869da122e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>93cc1f24-1a87-4023-8fba-f9ebaaff531b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'cusphone' and @name = 'cusphone']</value>
      <webElementGuid>c5b63611-508c-4799-bb84-fbb406488403</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
