<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code_zipcode</name>
   <tag></tag>
   <elementGuidId>9314ac4e-c0b0-4938-a01d-1a402b29f97c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zipcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zipcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>389842b0-c29b-43c3-9a75-055216e5e363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dde59d36-533c-46ec-86ae-c6f23d71e51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>c9ee5081-4f54-46c6-8b2a-7c4ebad5c396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>372501ca-e2f6-449e-9bba-28c2ae2fe7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>cust_zip_code</value>
      <webElementGuid>2965135b-1ff9-4d99-b7af-556dae9b9ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>f4d83f5d-0ad3-45de-8792-b54453d4301f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>9a4f24b1-c7ff-448a-900c-1143b92224f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-md ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>0356ac7b-f319-4263-b74b-fe2226ea6587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zipcode&quot;)</value>
      <webElementGuid>b1b618f8-8733-4dff-9ee5-e3f85a9124b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zipcode']</value>
      <webElementGuid>b75b5dc7-1dde-4b98-904b-c03df2208adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-pack-back-register/div/div/div/div/div/div/div/form/div[2]/div[3]/div/div[10]/div[2]/input</value>
      <webElementGuid>fedcf909-c3a3-4be6-8494-9b2c6abb2659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/input</value>
      <webElementGuid>943011d6-e88a-4b6e-ac3d-b82cf9513fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'zipcode' and @name = 'zipcode']</value>
      <webElementGuid>b1dd725c-bace-4f86-9b23-7b16897f4559</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
