<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Business Name_bussiness</name>
   <tag></tag>
   <elementGuidId>88c14e3a-baaf-4b6e-86d4-4d766b27e015</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bussiness</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bussiness']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fad59818-a7a0-40dc-a24f-838e6e1ca971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f68b2ff-8fb7-4c1a-bac8-7a85cbc7e663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>b4618d38-bce2-4c6b-9f1e-6c8e7ccab2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>contact_company_name</value>
      <webElementGuid>106187bf-c36e-4dde-a27a-0c17e56e4343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bussiness</value>
      <webElementGuid>6d66c1d6-5278-441a-8330-ca5dff26eff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bussiness</value>
      <webElementGuid>28836fcf-b8fd-4a80-9359-0fad7fe12b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-md ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>508f43b9-8bba-47a8-bdd2-aba9cc2e4db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bussiness&quot;)</value>
      <webElementGuid>f5b5ab30-1f83-48c3-911a-4aa0b727de36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bussiness']</value>
      <webElementGuid>188a11b7-ad16-4279-b367-e2481abb97a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-pack-back-register/div/div/div/div/div/div/div/form/div[2]/div[3]/div/div[3]/div[2]/input</value>
      <webElementGuid>b4a5bab1-126b-449a-ac4a-701bbc7872da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>3d4a5540-5e84-4e20-8f23-9966c4ff95b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bussiness' and @name = 'bussiness']</value>
      <webElementGuid>8331a299-0d47-4d21-a59e-24b3e9fe3956</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
