<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_close</name>
   <tag></tag>
   <elementGuidId>54352209-a274-4044-a297-c4eb4aed260c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='idBody']/ngb-modal-window/div/div/div/div/mat-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.material-icons.close.c-pointer.mat-icon-no-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>ad6fafd5-0ba9-43ed-acae-f8e6b851932e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b3e29379-9225-46a4-aead-45e425ed7a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>abf67cf3-4ad1-494a-95c5-81d495b200ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-icons close c-pointer mat-icon-no-color</value>
      <webElementGuid>b3806ee8-2742-4971-8b5f-cadfed36f55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3c526e00-53f3-414a-ae15-f6a5f74a9504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>3466703c-0e77-48d2-a03e-5425f03c6f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>2730c6f3-091f-4956-95aa-6448fbb7968a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idBody&quot;)/ngb-modal-window[@class=&quot;custom-toaster-modal d-block modal modal-dialog-centered fade show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;mt-42vh getlookuppopup&quot;]/div[@class=&quot;modal-header&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-icons close c-pointer mat-icon-no-color&quot;]</value>
      <webElementGuid>85cb3e8b-df8f-45b8-8d51-9864d8e74b3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='idBody']/ngb-modal-window/div/div/div/div/mat-icon</value>
      <webElementGuid>fc190e23-36da-49c9-88cc-063059bc7e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select User to Impersonate'])[1]/following::mat-icon[1]</value>
      <webElementGuid>571f0fa1-8cb3-4a3f-bb2b-1d7ced997776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logged in as'])[1]/following::mat-icon[1]</value>
      <webElementGuid>85431cd7-25ce-4124-bd69-03a541ce7842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pack Back Offers Auto-Replenishment'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>fd1152bf-18c1-4908-910e-a21390ddac20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='close']/parent::*</value>
      <webElementGuid>585bd8b9-84b2-4280-a642-1168db4ae341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-icon</value>
      <webElementGuid>1a9e0b78-535b-4bea-a439-72429d48c6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'close' or . = 'close')]</value>
      <webElementGuid>cbdb9dbd-80d4-4018-81b6-75d147ba7742</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
