<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_visibility</name>
   <tag></tag>
   <elementGuidId>fe9e9ca0-eb6e-4fb2-b3b4-1228a29a8146</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.material-icons.mat-icon-no-color.ng-tns-c129-2.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='idBody']/app-root/app-login/form/div/div[4]/div[3]/div[2]/mat-form-field/div/div/div[3]/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>022fb255-ed6d-4663-a38a-18a62120d64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>05e5dab5-0031-46e9-9682-5f000750d1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-icons mat-icon-no-color ng-tns-c129-2 ng-star-inserted</value>
      <webElementGuid>ff1ab73b-214a-4324-8120-6e1a178de0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>54b8a31d-9268-401d-a090-375e897572e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>6a9455a7-5dd4-49e4-af67-c5088f477e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> visibility </value>
      <webElementGuid>9b1cf9cd-2cb7-4c99-a3cc-744dbc1407a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idBody&quot;)/app-root[1]/app-login[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;form-horizontal mb0 ng-valid ng-dirty ng-touched&quot;]/div[@class=&quot;login_bg pos-relative&quot;]/div[@class=&quot;delighted-login scrollbar overflow-y-hidden corProjHeight&quot;]/div[@class=&quot;form-section elvs-form&quot;]/div[@class=&quot;row&quot;]/mat-form-field[@class=&quot;mat-form-field ng-tns-c129-2 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-has-label mat-form-field-hide-placeholder ng-valid ng-star-inserted mat-form-field-should-float ng-dirty ng-touched&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c129-2&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c129-2&quot;]/div[@class=&quot;mat-form-field-suffix ng-tns-c129-2 ng-star-inserted&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-icons mat-icon-no-color ng-tns-c129-2 ng-star-inserted&quot;]</value>
      <webElementGuid>900c5fd4-1672-4fdd-9929-660233c81a8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='idBody']/app-root/app-login/form/div/div[4]/div[3]/div[2]/mat-form-field/div/div/div[3]/mat-icon</value>
      <webElementGuid>6e45fda7-c1f7-49e4-ba6e-4145ae50580c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::mat-icon[1]</value>
      <webElementGuid>1b5ca58c-5459-47d2-ad6d-07f754c0d2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User name'])[1]/following::mat-icon[2]</value>
      <webElementGuid>a9ac27d0-a6a5-4331-9638-17ee67717397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/preceding::mat-icon[1]</value>
      <webElementGuid>9f295f89-b3f3-4f8d-906f-d106de7ad630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not a Member?'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>269b1911-760d-41fd-bace-dbc8db99b9e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='visibility']/parent::*</value>
      <webElementGuid>aba41c58-80a2-45be-8e04-671d1a3c2ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/mat-icon</value>
      <webElementGuid>1d9b267b-55c1-4628-922b-4940c6ea4c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = ' visibility ' or . = ' visibility ')]</value>
      <webElementGuid>5a30002d-0d65-46a1-a9dc-3ca7f2851b50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
