<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_News Releases</name>
   <tag></tag>
   <elementGuidId>c09ac829-0c46-4b31-96bb-59a017f341c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//nav[@id='block-nir-pid748-investorrelations']/ul/li/a)[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#serviceLineIcons > div.region.region-header > #block-nir-pid748-investorrelations > ul.menu.side-menu > li.side-menu__item > a.ir-news</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>23f61773-f453-4744-9438-9aec26a67289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/news-releases</value>
      <webElementGuid>6aa4ab11-650d-4bdd-b889-8176f953471e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ir-news</value>
      <webElementGuid>95ac6041-7054-4a3d-80d9-2c415e85028f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-link-system-path</name>
      <type>Main</type>
      <value>node/5816</value>
      <webElementGuid>e2f26c65-081d-49c4-82a4-f20635f19d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>News Releases</value>
      <webElementGuid>86d79a51-344a-4bac-86cf-a2eab34f4823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serviceLineIcons&quot;)/div[@class=&quot;region region-header&quot;]/nav[@id=&quot;block-nir-pid748-investorrelations&quot;]/ul[@class=&quot;menu side-menu&quot;]/li[@class=&quot;side-menu__item&quot;]/a[@class=&quot;ir-news&quot;]</value>
      <webElementGuid>4fb778fa-643f-49fd-8ea0-78547621f4ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//nav[@id='block-nir-pid748-investorrelations']/ul/li/a)[11]</value>
      <webElementGuid>2737de92-43c4-467a-a185-e8b6e8bc4fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'News Releases')])[2]</value>
      <webElementGuid>c6d894f5-ed9a-4e74-a5d6-f1b133651a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investor Relations'])[3]/following::a[1]</value>
      <webElementGuid>deeee132-ad21-42b9-a681-719bc9f3b838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::a[4]</value>
      <webElementGuid>42699e10-73c1-4149-800e-aa3e23509fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Events'])[2]/preceding::a[1]</value>
      <webElementGuid>fa4ea628-baf3-4e1b-b525-7848b98b40fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Presentations'])[2]/preceding::a[2]</value>
      <webElementGuid>7e25122e-d231-404a-b3bb-a89c6f4fbff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/news-releases')])[2]</value>
      <webElementGuid>d1d9ecc5-2442-40d9-a6bb-f325d8872ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/nav/ul/li/a</value>
      <webElementGuid>103c1e04-d18b-4271-9076-328941a92d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/news-releases' and (text() = 'News Releases' or . = 'News Releases')]</value>
      <webElementGuid>6ef922ae-f2dc-45bb-9de6-7fbaf4babcc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
