<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Presentations</name>
   <tag></tag>
   <elementGuidId>7c394035-ef68-472e-a1d8-8fa76b031b32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//nav[@id='block-nir-pid748-investorrelations']/ul/li[3]/a)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#serviceLineIcons > div.region.region-header > #block-nir-pid748-investorrelations > ul.menu.side-menu > li.side-menu__item > a.ir-presentations</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f9913d38-735d-4271-ad58-09aaf7fae8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/presentations</value>
      <webElementGuid>564ce780-5f67-42bc-9d42-896680cdbcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ir-presentations</value>
      <webElementGuid>84d5c433-3780-4d3d-b78e-7864feb19622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-link-system-path</name>
      <type>Main</type>
      <value>node/5831</value>
      <webElementGuid>0bce0a3b-d416-4ee8-a4d7-bf95aaaeaf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Presentations</value>
      <webElementGuid>49863381-dcf7-4032-8286-6b9375e38b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serviceLineIcons&quot;)/div[@class=&quot;region region-header&quot;]/nav[@id=&quot;block-nir-pid748-investorrelations&quot;]/ul[@class=&quot;menu side-menu&quot;]/li[@class=&quot;side-menu__item&quot;]/a[@class=&quot;ir-presentations&quot;]</value>
      <webElementGuid>b5ec762b-20a3-424e-aa33-dd1ead20d43e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//nav[@id='block-nir-pid748-investorrelations']/ul/li[3]/a)[2]</value>
      <webElementGuid>597fcff8-6dc2-416e-a935-8f01dee5d5a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Presentations')])[2]</value>
      <webElementGuid>c44878eb-e644-47b9-a13f-225da32371fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Events'])[2]/following::a[1]</value>
      <webElementGuid>e8550817-dd70-4e1d-8a3e-a2f22fe5904f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News Releases'])[2]/following::a[2]</value>
      <webElementGuid>84da7585-517d-493c-a557-5657db0a4f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEC Filings'])[2]/preceding::a[1]</value>
      <webElementGuid>cc802ad9-5569-4c41-9279-f752780c067d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annual Reports &amp; Sustainability'])[2]/preceding::a[2]</value>
      <webElementGuid>fcdf12e1-8f9b-4134-974e-0551d1105782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/presentations')])[2]</value>
      <webElementGuid>8c64c6ef-63f5-4ab4-b4de-077f9035594b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/nav/ul/li[3]/a</value>
      <webElementGuid>d6663bb6-d2f9-43cd-a5c0-5c8cb70192fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/presentations' and (text() = 'Presentations' or . = 'Presentations')]</value>
      <webElementGuid>a52aebb0-8087-4f67-a471-c3a7873077f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
