<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Residents</name>
   <tag></tag>
   <elementGuidId>6f4b7161-b21c-4fb5-8797-e61cb6c47847</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='residents']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#residents</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>75775a7f-cec7-4328-8412-6be367445b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>residents</value>
      <webElementGuid>902e763d-0830-4b7a-b5db-af6f160a4cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.republicservices.com/residents</value>
      <webElementGuid>dc6b46e8-25e1-4fd5-8fe5-40ff6992a196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Residents</value>
      <webElementGuid>cfa8a95c-839d-4f4c-94de-72eac6238edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;residents&quot;)</value>
      <webElementGuid>fe4a3b35-acf1-4df8-a94c-4c7218da85fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='residents']</value>
      <webElementGuid>3f368264-4bb4-4296-974e-c1351ccc5235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='main_menu']/li/a</value>
      <webElementGuid>c19315be-8a6e-4dd2-a85b-3862214d4332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Residents')]</value>
      <webElementGuid>8e41a354-1b63-4165-b5de-17dd0ca69977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investors Home'])[1]/following::a[2]</value>
      <webElementGuid>51a8a6fe-0863-4ea4-aad1-f52611e572ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Support'])[1]/following::a[4]</value>
      <webElementGuid>673e6f79-1b9a-45a7-8a1f-43e181bdb2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Businesses'])[1]/preceding::a[1]</value>
      <webElementGuid>72d2276d-d497-4a4d-b123-b30988a50e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Residents'])[2]/preceding::a[2]</value>
      <webElementGuid>ee4a7f27-a82b-4bcd-a17d-3c29a320d12b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Residents']/parent::*</value>
      <webElementGuid>fbdb072e-06c4-4ddd-9d45-a6ded35bed79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.republicservices.com/residents')]</value>
      <webElementGuid>029b8f69-d74f-47d5-bc77-3cfd3403b918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/a</value>
      <webElementGuid>3cd1fd32-291a-4471-81bc-652135974f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'residents' and @href = 'https://www.republicservices.com/residents' and (text() = 'Residents' or . = 'Residents')]</value>
      <webElementGuid>2457e018-29b1-452f-ac0c-996bb05658b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
