<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Predefined Themes_badge-b</name>
   <tag></tag>
   <elementGuidId>a4215306-d725-41cf-8664-cd946b7691f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapse1']/div/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>21526746-f510-4f74-81b6-5a86a075c9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>badge-b</value>
      <webElementGuid>570dcdf3-4470-49e9-b430-b5b6cc752fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse1&quot;)/div[@class=&quot;newtheme panel-body panel-body-b&quot;]/div[@class=&quot;form-group&quot;]/ul[@class=&quot;list-inline predefined-themes&quot;]/li[@class=&quot;p-r-10 outline-border ng-star-inserted&quot;]/a[@class=&quot;badge-b&quot;]</value>
      <webElementGuid>ed8c94fc-de79-4f2e-9cbd-a518fccab486</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse1']/div/div/ul/li[2]/a</value>
      <webElementGuid>d8fd4069-53a6-4f26-acf6-f942549abe5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[2]/a</value>
      <webElementGuid>2a53ee7e-dea6-4925-9e7f-0f74731978d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
