<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Message_message</name>
   <tag></tag>
   <elementGuidId>5e7dc867-a27b-4a3d-b7e8-354cbcd6ec50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='edit-message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ce90513a-0a2d-4122-8ac9-cedaefdf436c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-message</value>
      <webElementGuid>6cd2896c-ad60-4cde-b61d-f6e9f5ba2b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-message</value>
      <webElementGuid>552abaf6-2558-41b1-9276-fd89e5e8f078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>41732b85-44cd-4911-8120-7f822423c1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c9a9684a-fe5c-4df3-9a21-809289369224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>5ea20681-516b-4692-814e-cdbede818d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-textarea resize-vertical</value>
      <webElementGuid>3b543055-f564-4b2f-a1e3-99aa0eed3787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-message&quot;)</value>
      <webElementGuid>af2588c1-a743-4328-958b-6bd0e6ea9c6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='edit-message']</value>
      <webElementGuid>9efa51d9-acd8-4237-9bb7-8ce82347f0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='webform-submission-contact-us-2021-special-305-add-form']/div[6]/div/textarea</value>
      <webElementGuid>31d606cc-a58d-4c6a-93b8-7311b0960db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c033dfe0-7bd3-48cd-bea8-efea97915437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'edit-message' and @name = 'message']</value>
      <webElementGuid>f7c755e5-b1b8-4391-a1fe-ace17552df82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
