<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue as a guest</name>
   <tag></tag>
   <elementGuidId>aedc4a0e-eb35-48c7-9ed1-1f5444340208</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='guestlogin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#guestlogin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e5389ca0-57fb-4536-b809-656149957d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guestlogin</value>
      <webElementGuid>33244432-0231-4084-941c-583ed7c6e7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>white btn col-md-6 btn-sm btn-warning</value>
      <webElementGuid>55b65e7c-9fb9-4271-8afc-cad7da168a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Continue as a guest </value>
      <webElementGuid>78f8d834-9664-4815-92e3-5e08ca81867b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guestlogin&quot;)</value>
      <webElementGuid>e4c10aef-5428-409f-ae96-0420e588da43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='guestlogin']</value>
      <webElementGuid>366c8740-878e-447a-ac8e-cfa803c8803c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='idBody']/ngb-modal-window/div/div/div/div[2]/div/button[2]</value>
      <webElementGuid>1500f35e-7a76-4cda-a7e9-f121104696ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login/Create Login'])[1]/following::button[1]</value>
      <webElementGuid>1a2d545f-82ce-4145-bc19-92088257bfe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/following::button[2]</value>
      <webElementGuid>65fdc662-f0c0-4c0b-9c9c-8a4a4fecc1ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue as a guest']/parent::*</value>
      <webElementGuid>ca828510-e390-4ea3-8364-059f5ed06024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button[2]</value>
      <webElementGuid>797d8c59-55e1-4371-bde6-1e6f4e0f9a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'guestlogin' and (text() = ' Continue as a guest ' or . = ' Continue as a guest ')]</value>
      <webElementGuid>c25cf76d-8eae-44f3-8f76-ed1ed5c4e432</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
