<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Check Terms  Conditions</name>
   <tag></tag>
   <elementGuidId>dd344397-ef0e-437f-8783-ef327a084c05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ng-tns-c56-4.ng-star-inserted.ng-trigger.ng-trigger-flyInOut.ngx-toastr.toast-warning</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5a139574-b399-4dee-850c-d7584c450e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c56-4 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-warning</value>
      <webElementGuid>f579ad8b-795c-4352-9116-e62f8768ed01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Check Terms &amp; Conditions </value>
      <webElementGuid>3f17f169-6ac0-4e1d-9437-5d3d2136cf1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-container&quot;)/div[@class=&quot;ng-tns-c56-4 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-warning&quot;]</value>
      <webElementGuid>fbe9636c-ff8d-46b8-bd37-68277cbd1ca8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-container']/div</value>
      <webElementGuid>922a4b8a-235c-4859-89fd-f8bd1a2784c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select User to Impersonate'])[1]/following::div[8]</value>
      <webElementGuid>90928802-21ec-4602-8ce4-392dc27c809b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logged in as'])[1]/following::div[10]</value>
      <webElementGuid>eade64e8-3f3a-4358-8a85-0114737d9cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>0b87fd9c-9167-4c38-b52b-fa2b4b870761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Check Terms &amp; Conditions ' or . = ' Check Terms &amp; Conditions ')]</value>
      <webElementGuid>b7324dae-af75-4ff2-879b-fcbde6d1155d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
