<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , idBody, , )iframeclass_1ebc74</name>
   <tag></tag>
   <elementGuidId>e8ff80ce-2554-41d2-bfce-8cf6bdcf1209</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//iframe[@name='stripe_checkout_app'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>593034fa-77c8-4ee1-81c2-54bd6cbc77d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e2cfb79e-78cb-4be0-953a-722bd5b1612f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>12a2be13-0ef4-470f-a054-54464a801725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.stripe.com/v3/oivkx0oP8BgueCG8QFpDfA.html?distinct_id=8ee5c6d5-c572-f144-a9c5-9b7b5caaab4a</value>
      <webElementGuid>89cd1a92-ea27-4886-aa13-929f18976c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stripe_checkout_app</value>
      <webElementGuid>40e4e2d3-ed3d-4483-bf02-8e5f3948f2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stripe_checkout_app</value>
      <webElementGuid>62df4746-314d-4d3a-87d4-844040c981d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idBody&quot;)/iframe[@class=&quot;stripe_checkout_app&quot;]</value>
      <webElementGuid>ef26bcf9-ccec-4e56-8ae1-47001415d832</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//iframe[@name='stripe_checkout_app'])[2]</value>
      <webElementGuid>a12be7a1-e562-4290-90b7-ea6048aee06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='idBody']/iframe[2]</value>
      <webElementGuid>44db3b07-5fb0-4dc7-a3f0-d01e76953e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>e4edf18f-cbb2-4073-8ae7-f38739c66b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://checkout.stripe.com/v3/oivkx0oP8BgueCG8QFpDfA.html?distinct_id=8ee5c6d5-c572-f144-a9c5-9b7b5caaab4a' and @name = 'stripe_checkout_app']</value>
      <webElementGuid>df0c24c6-bd13-4e66-ac40-989829777f6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
