<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_cusphone</name>
   <tag></tag>
   <elementGuidId>e353565c-84df-491b-98c3-d721f98a5abc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cusphone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cusphone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a06e7ad-b0cc-44ca-85a3-c0929a82edd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73b1cfce-2500-4d06-93d2-f316ae79eae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>6e84357a-0ce5-4dc3-9e92-28d9990706e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>contact_phone</value>
      <webElementGuid>a8581e56-8db7-4d47-bba3-3aac155b28e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cusphone</value>
      <webElementGuid>95d3baad-95c3-4874-8260-769a5c0d46a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cusphone</value>
      <webElementGuid>ad21cd29-d447-48ef-a62e-dd44b6680ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>(000) 000-0000</value>
      <webElementGuid>c442e084-01a2-4624-986f-c559639cc75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>990fa9ac-9973-4f79-8b1a-27a94609ff9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cusphone&quot;)</value>
      <webElementGuid>2d3ed6be-14cc-46da-9e39-5cc6e6ee2624</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cusphone']</value>
      <webElementGuid>74ce387e-718b-4d3b-a484-d9f0bd7e5d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-checkout/div/div/div/div/div/div/div/div/div/form/div[4]/div[4]/div/input</value>
      <webElementGuid>6dc23a5d-6d2a-4580-9858-d28905b23390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/div/input</value>
      <webElementGuid>a4c82acf-fb23-473b-846b-aa767086af73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'cusphone' and @name = 'cusphone']</value>
      <webElementGuid>d1f6e3e4-1d0d-4826-b0c3-ea0c4413662d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
