<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pay 265.00_card_number</name>
   <tag></tag>
   <elementGuidId>b44c58c6-9bdb-459f-99d9-a53fd6981e27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='card_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38ec4a06-ceab-4abf-a2e7-aec756edb662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>308f641e-5f64-402a-b9eb-2c133a4eabec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control focus visa identified</value>
      <webElementGuid>b6b888ce-5792-4659-90d8-50e919e9e80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card_number</value>
      <webElementGuid>c70b455b-8b4a-4108-b626-02dabe02b572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>349e7389-0332-4b41-94ae-ad21b73b9dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-autocompletetype</name>
      <type>Main</type>
      <value>cc-number</value>
      <webElementGuid>f5202dec-3a09-4203-929e-d795bbaf0b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocompletetype</name>
      <type>Main</type>
      <value>cc-number</value>
      <webElementGuid>8ec4530a-b12c-4929-bfd9-f7dabc8693e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>31de73e1-868b-4ee7-90a5-ef7fb471364e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b69d7580-73aa-4979-b874-3dea2f491433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dccce2a4-10b3-436a-a696-81dff48b4531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Card number</value>
      <webElementGuid>bc40cb9b-2524-4560-b59b-5b90c353a477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card_number&quot;)</value>
      <webElementGuid>4ccc651f-1dd1-4135-b50b-82e70d850bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/check out order/Page_Pack Back/iframe_concat(id(, , idBody, , )iframeclass_1ebc74</value>
      <webElementGuid>ee926153-f81b-45d3-96f0-b0b60d8ad833</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='card_number']</value>
      <webElementGuid>00af357e-bc01-4acd-ad4a-bcea3afee67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e9206230-bfa5-4f53-97da-4adb4a4feb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'card_number' and @type = 'tel' and @placeholder = 'Card number']</value>
      <webElementGuid>daf5be84-1526-43aa-9829-711482642d71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
