<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Business Name_bussiness</name>
   <tag></tag>
   <elementGuidId>8ab2eafa-1c1c-4ab6-bb9f-02c5f79e949d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bussiness']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bussiness</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9fff88ef-0b14-4c6a-ab0e-e76ef0ef1d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c7156d8-8429-4bbe-bc92-279284a80e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>f5dac5c6-fd47-4455-b6c4-21241653f60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>bill_company_name</value>
      <webElementGuid>4a590e68-e3bd-4a3a-8146-93a153d39e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bussiness</value>
      <webElementGuid>467e2b37-5556-4204-b4ba-346db0e8e3a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bussiness</value>
      <webElementGuid>ea83f093-7b73-4103-ae5c-8f4b41ece65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>2a3f933f-3d6b-48c5-8636-b5fbdf4ceb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bussiness&quot;)</value>
      <webElementGuid>fb636fdf-786e-412b-8371-4d45bc2e1e14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bussiness']</value>
      <webElementGuid>3edb90ed-56df-4db0-88e3-a651352fd66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-checkout/div/div/div/div/div/div/div/div/div[2]/div[3]/div/form/div/div[2]/input</value>
      <webElementGuid>0a09a7da-13fd-4412-a0d8-a97f046abf83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/form/div/div[2]/input</value>
      <webElementGuid>3160e01a-5805-40a1-9419-00c8bb247aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bussiness' and @name = 'bussiness']</value>
      <webElementGuid>cc4987e8-336a-48df-b2c5-1446aa0df9bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
