<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pay 265.00</name>
   <tag></tag>
   <elementGuidId>8bd551a4-622d-4c83-92a5-f74a528171de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submitButton']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.iconTick</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>07b76402-90bf-474a-81d8-fae64466cb0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iconTick</value>
      <webElementGuid>e76ef737-e17b-40b0-a09a-8b9d4ebb8d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pay $265.00</value>
      <webElementGuid>7b9049c2-ff3e-49f7-afcc-9516eccbe7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitButton&quot;)/span[1]/span[@class=&quot;iconTick&quot;]</value>
      <webElementGuid>9f38597b-8b0b-4ddf-b1df-3aa79486cd07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/check out order/Page_Pack Back/iframe_concat(id(, , idBody, , )iframeclass_1ebc74</value>
      <webElementGuid>6f8976d9-ec8f-4158-ae4a-26e7b915de56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='submitButton']/span/span</value>
      <webElementGuid>30cfb14f-1aac-46da-871f-02e170febe74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='raj1@yopmail.com'])[1]/following::span[2]</value>
      <webElementGuid>de4d7810-dcb5-4c74-ae30-9c139e1e0f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buying 2 Products'])[1]/following::span[3]</value>
      <webElementGuid>2c440409-243b-4f90-86e6-661bdaeaa50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pay $265.00']/parent::*</value>
      <webElementGuid>57b606b4-b7ad-498b-886c-c5277f6ee0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>b415a8f0-dc09-4a24-a864-bfd357b3fcea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pay $265.00' or . = 'Pay $265.00')]</value>
      <webElementGuid>e16317a4-bb3c-4f03-ba0a-984319758c61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
