<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login</name>
   <tag></tag>
   <elementGuidId>f6fe7036-9ab0-4d43-8d87-10432b36595a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='idBody']/app-root/app-pack-back-main/app-pack-back-header/header/div/div/div/div[2]/ul[2]/li[6]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fs-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>03f5859e-26f5-4ed7-92f3-38d4fa305393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fs-white</value>
      <webElementGuid>d143e031-f3d5-440b-9f2f-3a61fbaa9b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>bdda57c1-a661-42ba-929d-6e631b69327b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idBody&quot;)/app-root[1]/app-pack-back-main[@class=&quot;ng-star-inserted&quot;]/app-pack-back-header[1]/header[1]/div[@class=&quot;web-hd&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;pd-l-00 header-right&quot;]/div[@class=&quot;logpart pl270&quot;]/ul[@class=&quot;header-logpart&quot;]/li[@class=&quot;mt-22px ml-min-55 c-pointer ng-star-inserted&quot;]/span[@class=&quot;fs-white&quot;]</value>
      <webElementGuid>18c644ab-d85d-46b0-bb6a-95074e342c38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='idBody']/app-root/app-pack-back-main/app-pack-back-header/header/div/div/div/div[2]/ul[2]/li[6]/span</value>
      <webElementGuid>f09a3f15-da45-4388-ac21-6b3417d856e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(800) 592-5489'])[1]/following::span[2]</value>
      <webElementGuid>3ed7e11a-8383-4077-ac8f-f3a2fe750b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Service'])[1]/following::span[3]</value>
      <webElementGuid>5a576c4d-0e6c-419b-87c2-1a465eac1620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create an Account'])[1]/preceding::span[2]</value>
      <webElementGuid>98a3a4b5-8945-4759-b060-157f578abeb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categories'])[1]/preceding::span[5]</value>
      <webElementGuid>08bdd9d7-20a7-4c74-9931-bf7aed63b559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>a3bd13aa-55fc-4895-b7cb-4749e1b21f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/span</value>
      <webElementGuid>8fc0f563-6da0-41a3-b137-082401d9656f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>b2d0ca93-b65e-485d-ba8d-788e4e4a1153</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
