<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shipped To You</name>
   <tag></tag>
   <elementGuidId>b9c93ac3-6ff0-4cf6-8602-463ecee06c34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ulId27']/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ulId27 > li.btm-clr > a.ionicon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3131005a-96e8-448f-84a0-38209f08b797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/pack-back/Orders</value>
      <webElementGuid>9e2cf9ee-1447-4ea0-9e9f-4f4b8e159c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>89f3a812-c140-4757-abbe-454a3406cf13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ionicon</value>
      <webElementGuid>0a082d2c-2a20-48aa-8fef-aadff4d38c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pack-back/Orders</value>
      <webElementGuid>bb2ebfbc-a020-48ee-8e09-4148e741b68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shipped To You</value>
      <webElementGuid>9a3c7c86-c6cd-433e-a4d0-c7d9dc66e029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ulId27&quot;)/li[@class=&quot;btm-clr&quot;]/a[@class=&quot;ionicon&quot;]</value>
      <webElementGuid>c0eb347a-f6bf-403e-bc85-f2aa417e5c6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ulId27']/li/a</value>
      <webElementGuid>57c2b195-6b1d-4934-ae6d-37025b3939d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Orders'])[1]/following::a[1]</value>
      <webElementGuid>07ff1372-1cb1-4d22-b88c-f7907cd8927d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='library_books'])[1]/following::a[1]</value>
      <webElementGuid>d241f7a6-4a5d-40c0-9d49-9a3e411d926e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipped For Recycling'])[1]/preceding::a[1]</value>
      <webElementGuid>5fb1628a-7f36-455d-bafc-e300d7899584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pack-back/Orders')]</value>
      <webElementGuid>503759b7-4ef8-4f71-a982-732a253caa96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li/a</value>
      <webElementGuid>bfe5af00-e2e5-4810-a14a-7df86c270b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/pack-back/Orders' and (text() = 'Shipped To You' or . = 'Shipped To You')]</value>
      <webElementGuid>b83cc97b-68e7-40ff-b964-511a22ad7069</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
