<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_(800) 592-5489_mainImg</name>
   <tag></tag>
   <elementGuidId>f43df8fd-2804-4b4e-b7a7-f8e80c9cb879</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='mainImg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainImg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>617f6470-788e-4b3a-88cc-ceeb0f6cf408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainImg</value>
      <webElementGuid>78ea398e-c576-4890-b703-356df54b0652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./assets/images/Logout.svg</value>
      <webElementGuid>50ff52f0-c6a9-43ab-9fea-705a9bd222d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logout</value>
      <webElementGuid>78b9c51f-889e-4df9-92e2-b89ed2a13c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>75%</value>
      <webElementGuid>0a4877a1-001d-4c4f-8ace-5787d0976b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>75%</value>
      <webElementGuid>fd53fe02-3de4-41ce-b711-3c4f90156817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placement</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>743ba6db-e670-433a-a8ba-999cb1101d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logout-icn</value>
      <webElementGuid>2592ae00-41a8-4cbf-ac03-a3d07f0e1bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip-2</value>
      <webElementGuid>e5efb137-1229-4b97-ab3a-436e0cf3ddc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainImg&quot;)</value>
      <webElementGuid>50ee822e-8b4f-433d-a1ef-f2c00444d33e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='mainImg']</value>
      <webElementGuid>10580337-3581-49ae-911b-1050f0ed0111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='idBody']/app-root/app-pack-back-main/app-pack-back-header/header/div/div/div/div[2]/ul[2]/li[6]/div/a/img</value>
      <webElementGuid>4d279ac6-88dd-4253-bdb8-513e363a4cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logout']</value>
      <webElementGuid>ea4fdf0b-7354-4b95-8488-8d07ce0d1cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/a/img</value>
      <webElementGuid>8d52f895-0315-42c0-ac9f-52037e5c7de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'mainImg' and @src = './assets/images/Logout.svg' and @alt = 'logout']</value>
      <webElementGuid>c87115e7-095e-43d0-9ba1-90142e9ad3c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
