<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Shipped For Recycling</name>
   <tag></tag>
   <elementGuidId>98276e17-fb34-4218-be79-3680f0a9efea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ulId27']/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>825b74e5-0b6f-494d-b07a-8c0ae8c38c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shipped For Recycling</value>
      <webElementGuid>4f3b4a3b-b46e-4057-9d15-451ff32068c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ulId27&quot;)/li[@class=&quot;btm-clr&quot;]/a[@class=&quot;ionicon&quot;]/span[1]</value>
      <webElementGuid>624dcb8b-d5e8-4f27-bda4-d8a4db0d1967</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ulId27']/li[2]/a/span</value>
      <webElementGuid>bafde6a9-4538-42fd-a160-e2acb0045881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipped To You'])[1]/following::span[1]</value>
      <webElementGuid>a11a561a-1a7d-43e8-b8d5-57d5ccf133f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Orders'])[1]/following::span[2]</value>
      <webElementGuid>b33a7915-bc51-4bc6-a410-9737e3e1a64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipped To You'])[2]/preceding::span[1]</value>
      <webElementGuid>d4945635-5366-4cfd-91b6-51f9a0616fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Questions or Concerns about an order,'])[1]/preceding::span[2]</value>
      <webElementGuid>5f92200b-e447-45e5-9b0b-be438072e4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shipped For Recycling']/parent::*</value>
      <webElementGuid>f702b4e4-8fc2-4b7e-ae1c-6dca984febab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li[2]/a/span</value>
      <webElementGuid>e71fcbc1-edc5-4355-a302-712594a38f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Shipped For Recycling' or . = 'Shipped For Recycling')]</value>
      <webElementGuid>2a634fb1-b810-4e0a-9a63-ccc2aa67ec2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
