<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Industrial Cleaning</name>
   <tag></tag>
   <elementGuidId>7e498742-b71c-414e-9f50-bb26ab1599c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-reason-for-inquiry-checkboxes']/div[4]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.js-form-item.form-item.js-form-type-checkbox.form-type-checkbox.js-form-item-reason-for-inquiry-checkboxes-industrial-cleaning.form-item-reason-for-inquiry-checkboxes-industrial-cleaning > label.option</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>91fc6e09-1a8e-4001-b08e-434f70396e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>edit-reason-for-inquiry-checkboxes-industrial-cleaning</value>
      <webElementGuid>8e921c46-28a3-4761-8896-c415cf726abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>bee1bf51-c14f-4e59-b6cc-c6a5d0ab4984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Industrial Cleaning</value>
      <webElementGuid>dc28a736-1cbd-4416-961b-fe0907176575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-reason-for-inquiry-checkboxes&quot;)/div[@class=&quot;js-form-item form-item js-form-type-checkbox form-type-checkbox js-form-item-reason-for-inquiry-checkboxes-industrial-cleaning form-item-reason-for-inquiry-checkboxes-industrial-cleaning&quot;]/label[@class=&quot;option&quot;]</value>
      <webElementGuid>f61b5300-8860-411b-b3ab-20f69bb4f8d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-reason-for-inquiry-checkboxes']/div[4]/label</value>
      <webElementGuid>376cc6f2-1f47-4cf3-841f-1c1a5af5778b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emergency, Disaster or Spill Response'])[1]/following::label[1]</value>
      <webElementGuid>1bbca5e7-d1c0-4e6a-a7b8-75498d5d1761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lab Pack'])[2]/following::label[2]</value>
      <webElementGuid>2ca5083b-c9ba-46ef-8bde-87be7bd8c8e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remediation'])[1]/preceding::label[1]</value>
      <webElementGuid>626f2998-e5b3-48fb-872e-eb8bc6c82ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other…'])[1]/preceding::label[2]</value>
      <webElementGuid>4ee188c6-17fb-4491-b677-7579a6b7d25f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Industrial Cleaning']/parent::*</value>
      <webElementGuid>569ed248-15a5-41d9-8771-a2cd743f914b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/label</value>
      <webElementGuid>6326ae4c-5ab6-4209-859e-f6b4f9972e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Industrial Cleaning' or . = 'Industrial Cleaning')]</value>
      <webElementGuid>c63f322c-970b-4a8b-acd4-54966162928a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
