<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invoice Address_address3</name>
   <tag></tag>
   <elementGuidId>f60e5aea-3ad9-4196-b3fa-27433889fc66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ada2fe38-47e4-462e-8611-78685300b170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>44833c2f-c882-4320-b1ef-0eca0749f56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>3b4258ed-3644-4e20-ab1e-621f4dd24a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>cust_address3</value>
      <webElementGuid>e6531e5c-f5fd-4faf-a325-0731cf23d4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address3</value>
      <webElementGuid>fc91aa9f-99fa-4a9b-a43d-c9f32b4d97a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address3</value>
      <webElementGuid>2ed3f372-352f-42cc-ac24-6a2e8162c097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-md ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b355e0d7-1fea-4491-ac72-5435d2678d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address3&quot;)</value>
      <webElementGuid>d970614c-28c5-484d-8e2f-7346f99c0da3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address3']</value>
      <webElementGuid>ff88681f-4e37-481e-9546-10d2b617d94f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-packback-profile/div/app-useraddress/div/div/div/div/div/div/form/div[3]/div/div[6]/div[2]/input</value>
      <webElementGuid>e8b44b5f-7f7e-4bdb-8b65-41c195cc7809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>3b7e3d9d-db42-4e55-a20d-75ec50b6932b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address3' and @name = 'address3']</value>
      <webElementGuid>db0d7cc3-8e6d-4358-be28-1d7778efe109</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
