<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to Cart</name>
   <tag></tag>
   <elementGuidId>b74dbd4c-16f6-4f45-ac95-0e9caae58c6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='rightcontent']/app-productlist/div/div[3]/div/div/div[3]/div/div/div[5]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8af53029-d8cb-4865-b809-6a0e38700fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm buttonInfo btn-addcart</value>
      <webElementGuid>df436e7e-a12e-4c5d-9f61-84cfa1691228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add to Cart </value>
      <webElementGuid>df517e09-3695-440c-a9a1-fa8dc5c71e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightcontent&quot;)/app-productlist[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;ptt00 mh900 pickup-part pack-back-part ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 col-sm-12 col-lg-3 col-xl-3 ng-star-inserted&quot;]/div[@class=&quot;productCard&quot;]/div[@class=&quot;card-body prd_details&quot;]/div[@class=&quot;d-flex btn-grp&quot;]/button[@class=&quot;btn btn-sm buttonInfo btn-addcart&quot;]</value>
      <webElementGuid>8b637ce5-0bca-49ec-a3d2-e5c0d3979a0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-productlist/div/div[3]/div/div/div[3]/div/div/div[5]/button</value>
      <webElementGuid>06a925bc-8a8f-4f01-beb8-7c1cb4bc93bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[3]/following::button[3]</value>
      <webElementGuid>48fdfaa6-77da-4986-943e-4753c95703a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 55.00'])[1]/following::button[3]</value>
      <webElementGuid>3466234a-8349-4c02-a60a-199eefd5c1f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Now'])[3]/preceding::button[1]</value>
      <webElementGuid>31ea4fd1-6ab8-42ce-90c2-440fdd5bff3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[5]/button</value>
      <webElementGuid>a8ac0a5e-25ff-49ef-a634-1e86240c321e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Add to Cart ' or . = ' Add to Cart ')]</value>
      <webElementGuid>46007408-04f6-4498-9f26-89c88a06d3de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
