<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Shipping Address_checkbox-custom posi_83da50</name>
   <tag></tag>
   <elementGuidId>718330bf-998b-4b5e-9175-974c78d912fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.checkbox-custom.position-absolute.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc79a4c2-a467-4be0-98dd-b9b8c719952d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>issame</value>
      <webElementGuid>738c1c2e-ddbb-4856-a1c6-cd837115996a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>23e17319-6f28-447f-b1e4-91e4bfb4fc1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>0945cc65-e027-4473-8a34-f87dc3908cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-custom position-absolute ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>d8121c67-a846-4ea3-909e-73c7a97790dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightcontent&quot;)/app-checkout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content ng-star-inserted&quot;]/div[@class=&quot;ptt00 mh900 pickup-part pack-back-part row m0&quot;]/div[@class=&quot;e-learning-body&quot;]/div[1]/div[@class=&quot;cards table_card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-md-12 col-lg-12 col-xl-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-md-6 col-lg-6 col-xl-6 shipping-address&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8 col-xl-8 col-md-8 col-sm-8&quot;]/input[@class=&quot;checkbox-custom position-absolute ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>bb080f2d-a0ed-4207-89c5-c208bc24487a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>4645baca-0acb-4ffc-ac11-5ed77c66ae46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-checkout/div/div/div/div/div/div/div/div/div[2]/div[3]/div[2]/form/div/div[2]/input</value>
      <webElementGuid>4299e871-0c76-430f-8676-f107d08cde22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div[2]/input</value>
      <webElementGuid>9de9b000-5170-42a2-a115-970f9c483a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>bdc22a77-57a8-4c59-9131-2adcf22ca829</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
