<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_lname</name>
   <tag></tag>
   <elementGuidId>a5a6660b-22a4-422e-9ac5-be37e56fdff4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bac89366-28fa-4faa-afcd-01b93cfe79fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>64926eaa-5a5f-4258-87c5-e5a513a66bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>044ba3f6-a19d-40d5-9fa2-fdf63c452f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>contact_last_name</value>
      <webElementGuid>9842261b-ef55-4a6a-bbb4-414d47cfaf08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lname</value>
      <webElementGuid>3044c304-1c96-44e3-9f37-c1fae262c115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lname</value>
      <webElementGuid>580612eb-931b-4ac1-abae-0baeef9dee09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6d073beb-34e0-42cc-8165-3759e5041d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lname&quot;)</value>
      <webElementGuid>a991c240-6826-4423-a6a1-eef063d5e6eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lname']</value>
      <webElementGuid>4502c99c-dace-4b9e-a6b3-b0b8e9b3800f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-checkout/div/div/div/div/div/div/div/div/div/form/div[3]/div[4]/input</value>
      <webElementGuid>7abdb412-a07e-4b39-ba8c-c6dc71e5d351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>a50575bc-8b7c-4a64-ad22-e2277219ff92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lname' and @name = 'lname']</value>
      <webElementGuid>1f3a0972-626b-4dd7-ac96-963c4665eba6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
