<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pay 220.00_cc-exp</name>
   <tag></tag>
   <elementGuidId>a2b15bc2-d386-4b6a-ae14-f569be805db5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cc-exp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cc-exp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48bf9b9d-bdb0-40f4-9b2a-154113d78c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c8843e6d-22b0-4be5-b41a-c1aeda7079ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control</value>
      <webElementGuid>64749946-875c-4088-836a-9e5108fc6db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cc-exp</value>
      <webElementGuid>1b47dea7-5e65-47be-9cb2-988729865e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>a656b750-b46d-4aab-8e46-dfdc1e724d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-autocompletetype</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f644a44b-2ec2-4e43-bb17-20c53f698245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocompletetype</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c83e2f7a-846f-4ea3-b5e1-782c7a649591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c179a1f2-fa2e-4d54-b12c-284e8d59c745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e7172d58-7ed7-4d73-baba-85bce522d630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>311c505b-2c19-4ee8-8834-e5d005476db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM / YY</value>
      <webElementGuid>71e3bd2a-0b14-4d1a-bb4f-6bd7e1ed244d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc-exp&quot;)</value>
      <webElementGuid>94d28b02-76ca-4bd4-b251-b5b145fd1395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/check out order/Page_Pack Back/Page_Pack Back/Guest - valid check out flow/Page_Pack Back/iframe_concat(id(, , idBody, , )iframeclass_1ebc74</value>
      <webElementGuid>1bc156c6-cfee-46d3-b26a-ed2d9395d1a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cc-exp']</value>
      <webElementGuid>e14a6be9-4a21-48ef-8bec-d0294c92374b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>eb9b6070-e943-4afd-8158-76ef37213946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cc-exp' and @type = 'tel' and @placeholder = 'MM / YY']</value>
      <webElementGuid>cdaa9e81-aab3-4e18-b1c2-d6549cb2d065</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
