<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Create an Account_cart_ctBtn</name>
   <tag></tag>
   <elementGuidId>2df5d8ff-7f93-42ba-a8b0-7464064ddf87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='idBody']/app-root/app-pack-back-main/app-pack-back-header/header/div/div/div/div[2]/ul[2]/li[9]/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.cart_ctBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6cfaf553-4123-40df-9c3d-e5c5963365a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./assets/images/pack-back/white/cart_image.svg</value>
      <webElementGuid>3ae32179-d348-4b71-a3a6-45a0315261b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart_ctBtn</value>
      <webElementGuid>b4236c66-3572-4fd7-9631-15e3371e77de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idBody&quot;)/app-root[1]/app-pack-back-main[@class=&quot;ng-star-inserted&quot;]/app-pack-back-header[1]/header[1]/div[@class=&quot;web-hd&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;pd-l-00 header-right&quot;]/div[@class=&quot;logpart pl270&quot;]/ul[@class=&quot;header-logpart&quot;]/li[@class=&quot;circle-icon&quot;]/div[@class=&quot;roundBtn roundBtnwhite bluue-btn c-pointer&quot;]/span[1]/img[@class=&quot;cart_ctBtn&quot;]</value>
      <webElementGuid>b0939cb2-33fa-4bdc-bc20-3f212f2d299e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='idBody']/app-root/app-pack-back-main/app-pack-back-header/header/div/div/div/div[2]/ul[2]/li[9]/div/span/img</value>
      <webElementGuid>0fa7f29d-5752-40e9-b8c4-0dacdbe3d4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>9a58db0a-95e8-487f-985b-ed6f7cb48bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './assets/images/pack-back/white/cart_image.svg']</value>
      <webElementGuid>bf67eca2-8005-4ee2-8b55-83f7bc6c22a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
