<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Track</name>
   <tag></tag>
   <elementGuidId>519a1645-e119-42fc-9ad1-285fa7a085f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='stApp_btnTrack']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#stApp_btnTrack</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3966a1ef-37c6-4feb-9fe6-747361b61f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>be5aaa54-9778-4533-9007-8db8a9add356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stApp_btnTrack</value>
      <webElementGuid>25c19e25-e566-4287-97c7-8bc205f3f11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ups-cta ups-cta_primary</value>
      <webElementGuid>ed0fd2a0-3909-45e7-9270-4fc98091c9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                      Track
                    </value>
      <webElementGuid>a285e5e0-e38f-4874-93dd-431c3742938e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stApp_btnTrack&quot;)</value>
      <webElementGuid>f36c80a9-8c25-4475-9456-d68e2c654005</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='stApp_btnTrack']</value>
      <webElementGuid>cf985bf3-39ca-4ef4-88fe-21142dfdc075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stApp_track_title']/div/div/div/div/div/div/button</value>
      <webElementGuid>386eb523-2bb1-4718-ac34-12ba97f67093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please provide a tracking number.'])[1]/following::button[1]</value>
      <webElementGuid>7f0bc985-33e5-4bf6-8672-3dd6c518f553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid'])[1]/following::button[1]</value>
      <webElementGuid>dc734861-3731-4518-bf0d-8b9df5a9eef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Track by Reference Number'])[1]/preceding::button[1]</value>
      <webElementGuid>9d0014a3-0f5e-4c56-b9ad-faa581c211f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import Tracking Numbers'])[1]/preceding::button[2]</value>
      <webElementGuid>1de58f1e-a127-4602-84a4-5c5f3133889e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div/div/button</value>
      <webElementGuid>33619498-8330-48af-b3e6-2f77e74f8bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'stApp_btnTrack' and (text() = '
                      Track
                    ' or . = '
                      Track
                    ')]</value>
      <webElementGuid>e560bc5e-7b05-40e6-bcc5-be892fe06194</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
