<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>897467b5-5639-4d3b-88d1-2dce9bb5ae14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ups-header_logo']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;UPS Home&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>eec5a5fe-0f87-476e-ade7-86f8ea05c14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/resources/images/UPS_logo.svg</value>
      <webElementGuid>2f648885-237b-47fc-99dd-0eb8116c930c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>UPS Home</value>
      <webElementGuid>32b83662-05b6-41c4-b556-5db37a50cf2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ups-header_logo&quot;)/img[1]</value>
      <webElementGuid>92c73ae6-4fff-46ec-8356-0e854a2285ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ups-header_logo']/img</value>
      <webElementGuid>f90f4218-8d6a-4382-8fac-1056c5c61740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='UPS Home']</value>
      <webElementGuid>15bb151c-01b7-45f3-a617-f91fd495ea2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>dc964c91-973a-462d-aff1-e793e8602606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/resources/images/UPS_logo.svg' and @alt = 'UPS Home']</value>
      <webElementGuid>2b4537ab-6791-484d-9a29-2e061aad71c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
