<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Republic Services, Inc. Reports First Qua_98322f</name>
   <tag></tag>
   <elementGuidId>165cba0d-afd6-40df-b085-f8c1b28e63d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wd_featurebox-standard_3521']/div/div[2]/p[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.inner_wrap > div.wd_featurebox > p:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ee26c1a6-1ea7-4b8b-aed5-c926f9bd7e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://media.republicservices.com/2023-04-27-Republic-Services,-Inc-Reports-First-Quarter-2023-Results</value>
      <webElementGuid>55611120-4f70-48ca-9f50-0f4f341578a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Republic Services, Inc. Reports First Quarter 2023 Results</value>
      <webElementGuid>3e4f4faf-7431-46f7-9582-75fdb4b5ecb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wd_featurebox-standard_3521&quot;)/div[@class=&quot;inner_wrap&quot;]/div[@class=&quot;wd_featurebox&quot;]/p[2]/a[1]</value>
      <webElementGuid>73a305c7-e556-41d7-abdc-91a5df0ce8a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wd_featurebox-standard_3521']/div/div[2]/p[2]/a</value>
      <webElementGuid>4a66dbf0-2207-4a7a-86f1-1b16ada3fb4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Republic Services, Inc. Reports First Quarter 2023 Results')]</value>
      <webElementGuid>43a7a3e6-6e0a-4faf-9bfb-185bf54a87c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMPANY NEWS'])[1]/following::a[1]</value>
      <webElementGuid>9610f7ea-753d-4205-a9f3-1a7cbd3938f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top Left Tile'])[1]/following::a[1]</value>
      <webElementGuid>c350e353-5c81-42d6-bfc5-2c86af5ea2b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top Right Tile'])[1]/preceding::a[1]</value>
      <webElementGuid>b189aaca-7510-4f43-b8ca-6a3894b33c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMPANY NEWS'])[2]/preceding::a[1]</value>
      <webElementGuid>ea7832b5-7de9-4a43-9d29-6eb4b32eb350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Republic Services, Inc. Reports First Quarter 2023 Results']/parent::*</value>
      <webElementGuid>cd26c1c6-f040-4f44-bb2c-f9e8a0782623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://media.republicservices.com/2023-04-27-Republic-Services,-Inc-Reports-First-Quarter-2023-Results')]</value>
      <webElementGuid>78e533da-b874-48b2-b511-7cdc83880ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div[2]/p[2]/a</value>
      <webElementGuid>2f1c35c3-1610-4c24-9413-e179cc1511bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://media.republicservices.com/2023-04-27-Republic-Services,-Inc-Reports-First-Quarter-2023-Results' and (text() = 'Republic Services, Inc. Reports First Quarter 2023 Results' or . = 'Republic Services, Inc. Reports First Quarter 2023 Results')]</value>
      <webElementGuid>924a1356-35d1-4cfb-8428-8aeb065329ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
