<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Check Terms  Conditions</name>
   <tag></tag>
   <elementGuidId>088aecd0-7df4-4754-bbfd-d7aed42d0f38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-container']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ng-tns-c56-5.ng-star-inserted.ng-trigger.ng-trigger-flyInOut.ngx-toastr.toast-warning</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7937afd7-a351-49c1-95d0-605bea13df81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c56-5 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-warning</value>
      <webElementGuid>ff1cdf4f-2dfe-469c-a432-3d07dc6f0838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Check Terms &amp; Conditions </value>
      <webElementGuid>100ee5e5-6c84-4f35-a18e-990bdbb562cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-container&quot;)/div[@class=&quot;ng-tns-c56-5 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-warning&quot;]</value>
      <webElementGuid>1ca01596-99b1-4d5e-963c-ba22ba33f0bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-container']/div</value>
      <webElementGuid>76a8e157-8275-42ad-9608-05493f6e90d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select User to Impersonate'])[1]/following::div[8]</value>
      <webElementGuid>dfd57e32-1804-4a9c-b67b-bd8fc0a63ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logged in as'])[1]/following::div[10]</value>
      <webElementGuid>233d3fad-f377-473b-b4d1-e10ba392e500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>663983b6-0c72-428e-bb9d-c726b57f6b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Check Terms &amp; Conditions ' or . = ' Check Terms &amp; Conditions ')]</value>
      <webElementGuid>ff02710e-7b28-48f0-b0c7-8dc36e0288b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
