<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , idBody, , )iframeclass_1ebc74</name>
   <tag></tag>
   <elementGuidId>eab61fdd-f987-4ab1-9e86-0abdfeb1f39c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//iframe[@name='stripe_checkout_app'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>41b925f9-7817-45e2-a202-182891d8590d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5a94144b-2f29-4362-952b-067ce453420d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bfeb4318-16e7-4282-b6d4-c7155644370a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.stripe.com/v3/oivkx0oP8BgueCG8QFpDfA.html?distinct_id=f949c3c4-f4f8-e49a-d5a6-539b4940dc1d</value>
      <webElementGuid>292104cf-28d8-432d-a14e-2adfe162801b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stripe_checkout_app</value>
      <webElementGuid>88169bca-9a04-4f81-afd6-cb60c3c0d005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stripe_checkout_app</value>
      <webElementGuid>d641aae3-d31e-4c58-b1d4-23e209eef2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idBody&quot;)/iframe[@class=&quot;stripe_checkout_app&quot;]</value>
      <webElementGuid>3bf9dfec-47fa-4296-b798-3822eb553f51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//iframe[@name='stripe_checkout_app'])[2]</value>
      <webElementGuid>df535e72-ce67-4c8e-aa08-e7a858d055b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='idBody']/iframe[2]</value>
      <webElementGuid>fd260ec9-2436-4f53-9f11-753d61586296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>19c83b2f-9758-472f-96bd-411841efe120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://checkout.stripe.com/v3/oivkx0oP8BgueCG8QFpDfA.html?distinct_id=f949c3c4-f4f8-e49a-d5a6-539b4940dc1d' and @name = 'stripe_checkout_app']</value>
      <webElementGuid>b52861e6-acfb-49dc-8040-3910a186afaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
