<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_BATTERIES_card-img-top ng-star-inserted</name>
   <tag></tag>
   <elementGuidId>75bbdb06-de0f-4a47-a07c-e668b9ce65c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='rightcontent']/app-packback-home/div/div[3]/div/div/div/div[3]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ef939889-2924-4888-8bc0-05abc43e4726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../../assets/images/pack-back/dashboard/Electronics Recycling Box -Small.png</value>
      <webElementGuid>0dfb9c79-40f9-433f-8d3a-296db6554d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top ng-star-inserted</value>
      <webElementGuid>d567d2fc-39aa-4501-b669-eeeefcb20232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightcontent&quot;)/app-packback-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;ptt00 mh900 pickup-part pack-back-part&quot;]/div[@class=&quot;e-learning-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-4 col-lg-4 col-md-6 col-sm-6 ng-star-inserted&quot;]/div[@class=&quot;cat_card&quot;]/img[@class=&quot;card-img-top ng-star-inserted&quot;]</value>
      <webElementGuid>ac9929b0-063d-4561-8ee2-273231d8119b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-packback-home/div/div[3]/div/div/div/div[3]/div/img</value>
      <webElementGuid>845690ac-0b53-43b5-b46b-f3137447e33d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/img</value>
      <webElementGuid>88862585-0ab7-4ec3-813c-aa5f4980d524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../../../../assets/images/pack-back/dashboard/Electronics Recycling Box -Small.png']</value>
      <webElementGuid>f0da2221-f588-4b2f-8db1-2b4265a7bd01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
