<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Quantity_fa fa-plus qtyIcon</name>
   <tag></tag>
   <elementGuidId>609b4939-b4c0-4dda-8433-7b5eda6e051f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='rightcontent']/app-productlist/div/div[3]/div/div/div/div/div/div[4]/div/button[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-plus.qtyIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>668d442c-0d8d-4aa1-95da-67f82518c4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus qtyIcon</value>
      <webElementGuid>57d4bfb6-72de-4aed-8c66-ad4b28835568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightcontent&quot;)/app-productlist[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;ptt00 mh900 pickup-part pack-back-part ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 col-sm-12 col-lg-3 col-xl-3 ng-star-inserted&quot;]/div[@class=&quot;productCard&quot;]/div[@class=&quot;card-body prd_details&quot;]/div[@class=&quot;d-inline-flex marginList&quot;]/div[@class=&quot;wrapper_btn&quot;]/button[@class=&quot;plusminus&quot;]/span[@class=&quot;fa fa-plus qtyIcon&quot;]</value>
      <webElementGuid>281de7f7-5152-4c5b-a574-26008524b2c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='rightcontent']/app-productlist/div/div[3]/div/div/div/div/div/div[4]/div/button[2]/span</value>
      <webElementGuid>627905a6-0bbb-4834-b15b-0fc14ad7ffe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>99f26eb8-b727-4911-af43-8888747394d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
