<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pay 370.00</name>
   <tag></tag>
   <elementGuidId>ccb816ae-6ade-42df-8184-8b85b142533d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submitButton']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.iconTick</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4ec3dd5f-c95b-4ab4-a554-64ce21b3cb74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iconTick</value>
      <webElementGuid>fc71e34f-689e-4fe0-9678-d20194801bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pay $370.00</value>
      <webElementGuid>81542ac8-f13b-4928-8cd0-5f71a33987e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitButton&quot;)/span[1]/span[@class=&quot;iconTick&quot;]</value>
      <webElementGuid>4439f6d3-5657-4f06-b7bc-5700d272b7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Home page/Checkout/Page_Pack Back/iframe_concat(id(, , idBody, , )iframeclass_1ebc74</value>
      <webElementGuid>5be2bafd-9c28-479d-8fc9-ec8fff755988</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='submitButton']/span/span</value>
      <webElementGuid>cf2e7574-f6ae-4bab-8947-49285b0a8c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='raj@yopmail.com'])[1]/following::span[2]</value>
      <webElementGuid>2cee71bd-b682-4c34-b794-8c90e442494f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buying 3 Products'])[1]/following::span[3]</value>
      <webElementGuid>8ef4a8dd-f2e5-41ad-9b27-06fcacfe5dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pay $370.00']/parent::*</value>
      <webElementGuid>b2c23263-9c74-485a-ab15-a1d53fb2b5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>e006a052-01e4-459f-b9e8-9a64c82e6f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pay $370.00' or . = 'Pay $370.00')]</value>
      <webElementGuid>af46bc14-b623-4282-9c18-e9e15eb71dc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
